// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/providers/cloudstack (interfaces: ProviderValidator,ValidatorRegistry)

// Package cloudstack is a generated GoMock package.
package cloudstack

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	decoder "github.com/aws/eks-anywhere/pkg/providers/cloudstack/decoder"
	types "github.com/aws/eks-anywhere/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockProviderValidator is a mock of ProviderValidator interface.
type MockProviderValidator struct {
	ctrl     *gomock.Controller
	recorder *MockProviderValidatorMockRecorder
}

// MockProviderValidatorMockRecorder is the mock recorder for MockProviderValidator.
type MockProviderValidatorMockRecorder struct {
	mock *MockProviderValidator
}

// NewMockProviderValidator creates a new mock instance.
func NewMockProviderValidator(ctrl *gomock.Controller) *MockProviderValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderValidator) EXPECT() *MockProviderValidatorMockRecorder {
	_ = "STUB: not implemented"

	// ValidateCloudStackDatacenterConfig mocks base method.
	return nil
}

func (m *MockProviderValidator) ValidateCloudStackDatacenterConfig(arg0 context.Context, arg1 *v1alpha1.CloudStackDatacenterConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateCloudStackDatacenterConfig indicates an expected call of ValidateCloudStackDatacenterConfig.
func (mr *MockProviderValidatorMockRecorder) ValidateCloudStackDatacenterConfig(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateClusterMachineConfigs mocks base method.
func (m *MockProviderValidator) ValidateClusterMachineConfigs(arg0 context.Context, arg1 *cluster.Spec) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateClusterMachineConfigs indicates an expected call of ValidateClusterMachineConfigs.
func (mr *MockProviderValidatorMockRecorder) ValidateClusterMachineConfigs(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateControlPlaneEndpointUniqueness mocks base method.
func (m *MockProviderValidator) ValidateControlPlaneEndpointUniqueness(arg0 string) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateControlPlaneEndpointUniqueness indicates an expected call of ValidateControlPlaneEndpointUniqueness.
func (mr *MockProviderValidatorMockRecorder) ValidateControlPlaneEndpointUniqueness(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateSecretsUnchanged mocks base method.
func (m *MockProviderValidator) ValidateSecretsUnchanged(arg0 context.Context, arg1 *types.Cluster, arg2 *decoder.CloudStackExecConfig, arg3 ProviderKubectlClient) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateSecretsUnchanged indicates an expected call of ValidateSecretsUnchanged.
func (mr *MockProviderValidatorMockRecorder) ValidateSecretsUnchanged(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockValidatorRegistry is a mock of ValidatorRegistry interface.
type MockValidatorRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorRegistryMockRecorder
}

// MockValidatorRegistryMockRecorder is the mock recorder for MockValidatorRegistry.
type MockValidatorRegistryMockRecorder struct {
	mock *MockValidatorRegistry
}

// NewMockValidatorRegistry creates a new mock instance.
func NewMockValidatorRegistry(ctrl *gomock.Controller) *MockValidatorRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorRegistry) EXPECT() *MockValidatorRegistryMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockValidatorRegistry) Get(arg0 *decoder.CloudStackExecConfig) (ProviderValidator, error) {
	_ = "STUB: not implemented"
	return *new(ProviderValidator), nil
}

// Get indicates an expected call of Get.
func (mr *MockValidatorRegistryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
