// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/networking/reconciler/reconciler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	controller "github.com/aws/eks-anywhere/pkg/controller"
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockCiliumReconciler is a mock of CiliumReconciler interface.
type MockCiliumReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockCiliumReconcilerMockRecorder
}

// MockCiliumReconcilerMockRecorder is the mock recorder for MockCiliumReconciler.
type MockCiliumReconcilerMockRecorder struct {
	mock *MockCiliumReconciler
}

// NewMockCiliumReconciler creates a new mock instance.
func NewMockCiliumReconciler(ctrl *gomock.Controller) *MockCiliumReconciler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCiliumReconciler) EXPECT() *MockCiliumReconcilerMockRecorder {
	_ = "STUB: not implemented"

	// Reconcile mocks base method.
	return nil
}

func (m *MockCiliumReconciler) Reconcile(ctx context.Context, logger logr.Logger, client client.Client, spec *cluster.Spec) (controller.Result, error) {
	_ = "STUB: not implemented"
	return *new(controller.Result), nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockCiliumReconcilerMockRecorder) Reconcile(ctx, logger, client, spec interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
