// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/crypto/certificategen.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCertificateGenerator is a mock of CertificateGenerator interface.
type MockCertificateGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateGeneratorMockRecorder
}

// MockCertificateGeneratorMockRecorder is the mock recorder for MockCertificateGenerator.
type MockCertificateGeneratorMockRecorder struct {
	mock *MockCertificateGenerator
}

// NewMockCertificateGenerator creates a new mock instance.
func NewMockCertificateGenerator(ctrl *gomock.Controller) *MockCertificateGenerator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateGenerator) EXPECT() *MockCertificateGeneratorMockRecorder {
	_ = "STUB: not implemented"

	// GenerateIamAuthSelfSignCertKeyPair mocks base method.
	return nil
}

func (m *MockCertificateGenerator) GenerateIamAuthSelfSignCertKeyPair() ([]byte, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// GenerateIamAuthSelfSignCertKeyPair indicates an expected call of GenerateIamAuthSelfSignCertKeyPair.
func (mr *MockCertificateGeneratorMockRecorder) GenerateIamAuthSelfSignCertKeyPair() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
