// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/gitops/flux (interfaces: FluxClient,KubeClient,GitOpsFluxClient,GitClient,Templater)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	config "github.com/aws/eks-anywhere/pkg/config"
	executables "github.com/aws/eks-anywhere/pkg/executables"
	filewriter "github.com/aws/eks-anywhere/pkg/filewriter"
	git "github.com/aws/eks-anywhere/pkg/git"
	types "github.com/aws/eks-anywhere/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockFluxClient is a mock of FluxClient interface.
type MockFluxClient struct {
	ctrl     *gomock.Controller
	recorder *MockFluxClientMockRecorder
}

// MockFluxClientMockRecorder is the mock recorder for MockFluxClient.
type MockFluxClientMockRecorder struct {
	mock *MockFluxClient
}

// NewMockFluxClient creates a new mock instance.
func NewMockFluxClient(ctrl *gomock.Controller) *MockFluxClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFluxClient) EXPECT() *MockFluxClientMockRecorder {
	_ = "STUB: not implemented"

	// BootstrapGit mocks base method.
	return nil
}

func (m *MockFluxClient) BootstrapGit(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig, arg3 *config.CliConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGit indicates an expected call of BootstrapGit.
func (mr *MockFluxClientMockRecorder) BootstrapGit(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGithub mocks base method.
func (m *MockFluxClient) BootstrapGithub(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGithub indicates an expected call of BootstrapGithub.
func (mr *MockFluxClientMockRecorder) BootstrapGithub(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile mocks base method.
func (m *MockFluxClient) Reconcile(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockFluxClientMockRecorder) Reconcile(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall mocks base method.
func (m *MockFluxClient) Uninstall(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockFluxClientMockRecorder) Uninstall(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubeClient is a mock of KubeClient interface.
type MockKubeClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeClientMockRecorder
}

// MockKubeClientMockRecorder is the mock recorder for MockKubeClient.
type MockKubeClientMockRecorder struct {
	mock *MockKubeClient
}

// NewMockKubeClient creates a new mock instance.
func NewMockKubeClient(ctrl *gomock.Controller) *MockKubeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeClient) EXPECT() *MockKubeClientMockRecorder {
	_ = "STUB: not implemented"

	// DeleteSecret mocks base method.
	return nil
}

func (m *MockKubeClient) DeleteSecret(arg0 context.Context, arg1 *types.Cluster, arg2, arg3 string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockKubeClientMockRecorder) DeleteSecret(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEksaCluster mocks base method.
func (m *MockKubeClient) GetEksaCluster(arg0 context.Context, arg1 *types.Cluster, arg2 string) (*v1alpha1.Cluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEksaCluster indicates an expected call of GetEksaCluster.
func (mr *MockKubeClientMockRecorder) GetEksaCluster(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveAnnotation mocks base method.
func (m *MockKubeClient) RemoveAnnotation(arg0 context.Context, arg1, arg2, arg3 string, arg4 ...executables.KubectlOpt) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveAnnotation indicates an expected call of RemoveAnnotation.
func (mr *MockKubeClientMockRecorder) RemoveAnnotation(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation mocks base method.
func (m *MockKubeClient) UpdateAnnotation(arg0 context.Context, arg1, arg2 string, arg3 map[string]string, arg4 ...executables.KubectlOpt) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation indicates an expected call of UpdateAnnotation.
func (mr *MockKubeClientMockRecorder) UpdateAnnotation(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGitOpsFluxClient is a mock of GitOpsFluxClient interface.
type MockGitOpsFluxClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitOpsFluxClientMockRecorder
}

// MockGitOpsFluxClientMockRecorder is the mock recorder for MockGitOpsFluxClient.
type MockGitOpsFluxClientMockRecorder struct {
	mock *MockGitOpsFluxClient
}

// NewMockGitOpsFluxClient creates a new mock instance.
func NewMockGitOpsFluxClient(ctrl *gomock.Controller) *MockGitOpsFluxClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitOpsFluxClient) EXPECT() *MockGitOpsFluxClientMockRecorder {
	_ = "STUB: not implemented"

	// BootstrapGit mocks base method.
	return nil
}

func (m *MockGitOpsFluxClient) BootstrapGit(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig, arg3 *config.CliConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGit indicates an expected call of BootstrapGit.
func (mr *MockGitOpsFluxClientMockRecorder) BootstrapGit(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGithub mocks base method.
func (m *MockGitOpsFluxClient) BootstrapGithub(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// BootstrapGithub indicates an expected call of BootstrapGithub.
func (mr *MockGitOpsFluxClientMockRecorder) BootstrapGithub(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSystemSecret mocks base method.
func (m *MockGitOpsFluxClient) DeleteSystemSecret(arg0 context.Context, arg1 *types.Cluster, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSystemSecret indicates an expected call of DeleteSystemSecret.
func (mr *MockGitOpsFluxClientMockRecorder) DeleteSystemSecret(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DisableResourceReconcile mocks base method.
func (m *MockGitOpsFluxClient) DisableResourceReconcile(arg0 context.Context, arg1 *types.Cluster, arg2, arg3, arg4 string) error {
	_ = "STUB: not implemented"
	return nil
}

// DisableResourceReconcile indicates an expected call of DisableResourceReconcile.
func (mr *MockGitOpsFluxClientMockRecorder) DisableResourceReconcile(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EnableResourceReconcile mocks base method.
func (m *MockGitOpsFluxClient) EnableResourceReconcile(arg0 context.Context, arg1 *types.Cluster, arg2, arg3, arg4 string) error {
	_ = "STUB: not implemented"
	return nil
}

// EnableResourceReconcile indicates an expected call of EnableResourceReconcile.
func (mr *MockGitOpsFluxClientMockRecorder) EnableResourceReconcile(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ForceReconcile mocks base method.
func (m *MockGitOpsFluxClient) ForceReconcile(arg0 context.Context, arg1 *types.Cluster, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// ForceReconcile indicates an expected call of ForceReconcile.
func (mr *MockGitOpsFluxClientMockRecorder) ForceReconcile(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCluster mocks base method.
func (m *MockGitOpsFluxClient) GetCluster(arg0 context.Context, arg1 *types.Cluster, arg2 *cluster.Spec) (*v1alpha1.Cluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockGitOpsFluxClientMockRecorder) GetCluster(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile mocks base method.
func (m *MockGitOpsFluxClient) Reconcile(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockGitOpsFluxClientMockRecorder) Reconcile(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall mocks base method.
func (m *MockGitOpsFluxClient) Uninstall(arg0 context.Context, arg1 *types.Cluster, arg2 *v1alpha1.FluxConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockGitOpsFluxClientMockRecorder) Uninstall(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGitClient is a mock of GitClient interface.
type MockGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitClientMockRecorder
}

// MockGitClientMockRecorder is the mock recorder for MockGitClient.
type MockGitClientMockRecorder struct {
	mock *MockGitClient
}

// NewMockGitClient creates a new mock instance.
func NewMockGitClient(ctrl *gomock.Controller) *MockGitClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitClient) EXPECT() *MockGitClientMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockGitClient) Add(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockGitClientMockRecorder) Add(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Branch mocks base method.
func (m *MockGitClient) Branch(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Branch indicates an expected call of Branch.
func (mr *MockGitClientMockRecorder) Branch(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Clone mocks base method.
func (m *MockGitClient) Clone(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Clone indicates an expected call of Clone.
func (mr *MockGitClientMockRecorder) Clone(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Commit mocks base method.
func (m *MockGitClient) Commit(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockGitClientMockRecorder) Commit(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateRepo mocks base method.
func (m *MockGitClient) CreateRepo(arg0 context.Context, arg1 git.CreateRepoOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateRepo indicates an expected call of CreateRepo.
func (mr *MockGitClientMockRecorder) CreateRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRepo mocks base method.
func (m *MockGitClient) GetRepo(arg0 context.Context) (*git.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockGitClientMockRecorder) GetRepo(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockGitClient) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockGitClientMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// PathExists mocks base method.
func (m *MockGitClient) PathExists(arg0 context.Context, arg1, arg2, arg3, arg4 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// PathExists indicates an expected call of PathExists.
func (mr *MockGitClientMockRecorder) PathExists(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Pull mocks base method.
func (m *MockGitClient) Pull(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// Pull indicates an expected call of Pull.
func (mr *MockGitClientMockRecorder) Pull(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Push mocks base method.
func (m *MockGitClient) Push(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Push indicates an expected call of Push.
func (mr *MockGitClientMockRecorder) Push(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Remove mocks base method.
func (m *MockGitClient) Remove(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Remove indicates an expected call of Remove.
func (mr *MockGitClientMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTemplater is a mock of Templater interface.
type MockTemplater struct {
	ctrl     *gomock.Controller
	recorder *MockTemplaterMockRecorder
}

// MockTemplaterMockRecorder is the mock recorder for MockTemplater.
type MockTemplaterMockRecorder struct {
	mock *MockTemplater
}

// NewMockTemplater creates a new mock instance.
func NewMockTemplater(ctrl *gomock.Controller) *MockTemplater {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplater) EXPECT() *MockTemplaterMockRecorder {
	_ = "STUB: not implemented"

	// WriteToFile mocks base method.
	return nil
}

func (m *MockTemplater) WriteToFile(arg0 string, arg1 interface{}, arg2 string, arg3 ...filewriter.FileOptionsFunc) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// WriteToFile indicates an expected call of WriteToFile.
func (mr *MockTemplaterMockRecorder) WriteToFile(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
