// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/bootstrapper (interfaces: ClusterClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	bootstrapper "github.com/aws/eks-anywhere/pkg/bootstrapper"
	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	types "github.com/aws/eks-anywhere/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockClusterClient is a mock of ClusterClient interface.
type MockClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientMockRecorder
}

// MockClusterClientMockRecorder is the mock recorder for MockClusterClient.
type MockClusterClientMockRecorder struct {
	mock *MockClusterClient
}

// NewMockClusterClient creates a new mock instance.
func NewMockClusterClient(ctrl *gomock.Controller) *MockClusterClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClient) EXPECT() *MockClusterClientMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *MockClusterClient) Apply(arg0 context.Context, arg1 *types.Cluster, arg2 []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Apply indicates an expected call of Apply.
func (mr *MockClusterClientMockRecorder) Apply(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateBootstrapCluster mocks base method.
func (m *MockClusterClient) CreateBootstrapCluster(arg0 context.Context, arg1 *cluster.Spec, arg2 ...bootstrapper.BootstrapClusterClientOption) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// CreateBootstrapCluster indicates an expected call of CreateBootstrapCluster.
func (mr *MockClusterClientMockRecorder) CreateBootstrapCluster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateNamespace mocks base method.
func (m *MockClusterClient) CreateNamespace(arg0 context.Context, arg1, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockClusterClientMockRecorder) CreateNamespace(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteKindCluster mocks base method.
func (m *MockClusterClient) DeleteKindCluster(arg0 context.Context, arg1 *types.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteKindCluster indicates an expected call of DeleteKindCluster.
func (mr *MockClusterClientMockRecorder) DeleteKindCluster(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCAPIClusterCRD mocks base method.
func (m *MockClusterClient) GetCAPIClusterCRD(arg0 context.Context, arg1 *types.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// GetCAPIClusterCRD indicates an expected call of GetCAPIClusterCRD.
func (mr *MockClusterClientMockRecorder) GetCAPIClusterCRD(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCAPIClusters mocks base method.
func (m *MockClusterClient) GetCAPIClusters(arg0 context.Context, arg1 *types.Cluster) ([]types.CAPICluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCAPIClusters indicates an expected call of GetCAPIClusters.
func (mr *MockClusterClientMockRecorder) GetCAPIClusters(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetKindClusterKubeconfig mocks base method.
func (m *MockClusterClient) GetKindClusterKubeconfig(arg0 context.Context, arg1 string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetKindClusterKubeconfig indicates an expected call of GetKindClusterKubeconfig.
func (mr *MockClusterClientMockRecorder) GetKindClusterKubeconfig(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// KindClusterExists mocks base method.
func (m *MockClusterClient) KindClusterExists(arg0 context.Context, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// KindClusterExists indicates an expected call of KindClusterExists.
func (mr *MockClusterClientMockRecorder) KindClusterExists(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithEnv mocks base method.
func (m *MockClusterClient) WithEnv(arg0 map[string]string) bootstrapper.BootstrapClusterClientOption {
	_ = "STUB: not implemented"
	return *new(bootstrapper.BootstrapClusterClientOption)
}

// WithEnv indicates an expected call of WithEnv.
func (mr *MockClusterClientMockRecorder) WithEnv(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithExtraDockerMounts mocks base method.
func (m *MockClusterClient) WithExtraDockerMounts() bootstrapper.BootstrapClusterClientOption {
	_ = "STUB: not implemented"
	return *new(bootstrapper.BootstrapClusterClientOption)
}

// WithExtraDockerMounts indicates an expected call of WithExtraDockerMounts.
func (mr *MockClusterClientMockRecorder) WithExtraDockerMounts() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithExtraPortMappings mocks base method.
func (m *MockClusterClient) WithExtraPortMappings(arg0 []int) bootstrapper.BootstrapClusterClientOption {
	_ = "STUB: not implemented"
	return *new(bootstrapper.BootstrapClusterClientOption)
}

// WithExtraPortMappings indicates an expected call of WithExtraPortMappings.
func (mr *MockClusterClientMockRecorder) WithExtraPortMappings(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
