// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/tinkerbell/stack/stack.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	helm "github.com/aws/eks-anywhere/pkg/helm"
	stack "github.com/aws/eks-anywhere/pkg/providers/tinkerbell/stack"
	v1alpha1 "github.com/aws/eks-anywhere/release/api/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockDocker is a mock of Docker interface.
type MockDocker struct {
	ctrl     *gomock.Controller
	recorder *MockDockerMockRecorder
}

// MockDockerMockRecorder is the mock recorder for MockDocker.
type MockDockerMockRecorder struct {
	mock *MockDocker
}

// NewMockDocker creates a new mock instance.
func NewMockDocker(ctrl *gomock.Controller) *MockDocker { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocker) EXPECT() *MockDockerMockRecorder {
	_ = "STUB: not implemented"

	// CheckContainerExistence mocks base method.
	return nil
}

func (m *MockDocker) CheckContainerExistence(ctx context.Context, name string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// CheckContainerExistence indicates an expected call of CheckContainerExistence.
func (mr *MockDockerMockRecorder) CheckContainerExistence(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ForceRemove mocks base method.
func (m *MockDocker) ForceRemove(ctx context.Context, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// ForceRemove indicates an expected call of ForceRemove.
func (mr *MockDockerMockRecorder) ForceRemove(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockDocker) Run(ctx context.Context, image, name string, cmd []string, flags ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Run indicates an expected call of Run.
func (mr *MockDockerMockRecorder) Run(ctx, image, name, cmd interface{}, flags ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockHelm is a mock of Helm interface.
type MockHelm struct {
	ctrl     *gomock.Controller
	recorder *MockHelmMockRecorder
}

// MockHelmMockRecorder is the mock recorder for MockHelm.
type MockHelmMockRecorder struct {
	mock *MockHelm
}

// NewMockHelm creates a new mock instance.
func NewMockHelm(ctrl *gomock.Controller) *MockHelm { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelm) EXPECT() *MockHelmMockRecorder {
	_ = "STUB: not implemented"

	// ListCharts mocks base method.
	return nil
}

func (m *MockHelm) ListCharts(ctx context.Context, kubeconfigFilePath, filter, namespace string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCharts indicates an expected call of ListCharts.
func (mr *MockHelmMockRecorder) ListCharts(ctx, kubeconfigFilePath, filter, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegistryLogin mocks base method.
func (m *MockHelm) RegistryLogin(ctx context.Context, endpoint, username, password string) error {
	_ = "STUB: not implemented"
	return nil
}

// RegistryLogin indicates an expected call of RegistryLogin.
func (mr *MockHelmMockRecorder) RegistryLogin(ctx, endpoint, username, password interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall mocks base method.
func (m *MockHelm) Uninstall(ctx context.Context, chart, kubeconfigFilePath, namespace string, opts ...helm.Opt) error {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockHelmMockRecorder) Uninstall(ctx, chart, kubeconfigFilePath, namespace interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeInstallChartWithValuesFile mocks base method.
func (m *MockHelm) UpgradeInstallChartWithValuesFile(ctx context.Context, chart, ociURI, version, kubeconfigFilePath, namespace, valuesFilePath string, opts ...helm.Opt) error {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeInstallChartWithValuesFile indicates an expected call of UpgradeInstallChartWithValuesFile.
func (mr *MockHelmMockRecorder) UpgradeInstallChartWithValuesFile(ctx, chart, ociURI, version, kubeconfigFilePath, namespace, valuesFilePath interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStackInstaller is a mock of StackInstaller interface.
type MockStackInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockStackInstallerMockRecorder
}

// MockStackInstallerMockRecorder is the mock recorder for MockStackInstaller.
type MockStackInstallerMockRecorder struct {
	mock *MockStackInstaller
}

// NewMockStackInstaller creates a new mock instance.
func NewMockStackInstaller(ctrl *gomock.Controller) *MockStackInstaller {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackInstaller) EXPECT() *MockStackInstallerMockRecorder {
	_ = "STUB: not implemented"

	// AddNoProxyIP mocks base method.
	return nil
}

func (m *MockStackInstaller) AddNoProxyIP(IP string) { _ = "STUB: not implemented"; return }

// AddNoProxyIP indicates an expected call of AddNoProxyIP.
func (mr *MockStackInstallerMockRecorder) AddNoProxyIP(IP interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CleanupLocalBoots mocks base method.
func (m *MockStackInstaller) CleanupLocalBoots(ctx context.Context, forceCleanup bool) error {
	_ = "STUB: not implemented"
	return nil
}

// CleanupLocalBoots indicates an expected call of CleanupLocalBoots.
func (mr *MockStackInstallerMockRecorder) CleanupLocalBoots(ctx, forceCleanup interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockStackInstaller) GetNamespace() string { _ = "STUB: not implemented"; return "" }

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockStackInstallerMockRecorder) GetNamespace() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasChart mocks base method.
func (m *MockStackInstaller) HasChart(ctx context.Context, chartName, kubeconfig, namespace string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// HasChart indicates an expected call of HasChart.
func (mr *MockStackInstallerMockRecorder) HasChart(ctx, chartName, kubeconfig, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Install mocks base method.
func (m *MockStackInstaller) Install(ctx context.Context, bundle v1alpha1.TinkerbellBundle, tinkerbellIP, kubeconfig, hookOverride string, opts ...stack.InstallOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Install indicates an expected call of Install.
func (mr *MockStackInstallerMockRecorder) Install(ctx, bundle, tinkerbellIP, kubeconfig, hookOverride interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UninstallChart mocks base method.
func (m *MockStackInstaller) UninstallChart(ctx context.Context, chartName, kubeconfig, namespace string) error {
	_ = "STUB: not implemented"
	return nil
}

// UninstallChart indicates an expected call of UninstallChart.
func (mr *MockStackInstallerMockRecorder) UninstallChart(ctx, chartName, kubeconfig, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UninstallLocal mocks base method.
func (m *MockStackInstaller) UninstallLocal(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// UninstallLocal indicates an expected call of UninstallLocal.
func (mr *MockStackInstallerMockRecorder) UninstallLocal(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Upgrade mocks base method.
func (m *MockStackInstaller) Upgrade(arg0 context.Context, arg1 v1alpha1.TinkerbellBundle, tinkerbellIP, kubeconfig, hookOverride string, opts ...stack.InstallOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockStackInstallerMockRecorder) Upgrade(arg0, arg1, tinkerbellIP, kubeconfig, hookOverride interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeInstallCRDs mocks base method.
func (m *MockStackInstaller) UpgradeInstallCRDs(ctx context.Context, bundle v1alpha1.TinkerbellBundle, kubeconfig string, opts ...stack.InstallOption) error {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeInstallCRDs indicates an expected call of UpgradeInstallCRDs.
func (mr *MockStackInstallerMockRecorder) UpgradeInstallCRDs(ctx, bundle, kubeconfig interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeLegacy mocks base method.
func (m *MockStackInstaller) UpgradeLegacy(ctx context.Context, bundle v1alpha1.TinkerbellBundle, kubeconfig string, opts ...stack.InstallOption) error {
	_ = "STUB: not implemented"
	return nil
}

// UpgradeLegacy indicates an expected call of UpgradeLegacy.
func (mr *MockStackInstallerMockRecorder) UpgradeLegacy(ctx, bundle, kubeconfig interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
