// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/eksctl-anywhere/cmd/internal/commands/artifacts/download.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/release/api/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	_ = "STUB: not implemented"

	// ReadBundlesForVersion mocks base method.
	return nil
}

func (m *MockReader) ReadBundlesForVersion(eksaVersion string) (*v1alpha1.Bundles, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadBundlesForVersion indicates an expected call of ReadBundlesForVersion.
func (mr *MockReaderMockRecorder) ReadBundlesForVersion(eksaVersion interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadChartsFromBundles mocks base method.
func (m *MockReader) ReadChartsFromBundles(ctx context.Context, bundles *v1alpha1.Bundles) []v1alpha1.Image {
	_ = "STUB: not implemented"
	return nil
}

// ReadChartsFromBundles indicates an expected call of ReadChartsFromBundles.
func (mr *MockReaderMockRecorder) ReadChartsFromBundles(ctx, bundles interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadImagesFromBundles mocks base method.
func (m *MockReader) ReadImagesFromBundles(ctx context.Context, bundles *v1alpha1.Bundles) ([]v1alpha1.Image, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadImagesFromBundles indicates an expected call of ReadImagesFromBundles.
func (mr *MockReaderMockRecorder) ReadImagesFromBundles(ctx, bundles interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockImageMover is a mock of ImageMover interface.
type MockImageMover struct {
	ctrl     *gomock.Controller
	recorder *MockImageMoverMockRecorder
}

// MockImageMoverMockRecorder is the mock recorder for MockImageMover.
type MockImageMoverMockRecorder struct {
	mock *MockImageMover
}

// NewMockImageMover creates a new mock instance.
func NewMockImageMover(ctrl *gomock.Controller) *MockImageMover {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageMover) EXPECT() *MockImageMoverMockRecorder {
	_ = "STUB: not implemented"

	// Move mocks base method.
	return nil
}

func (m *MockImageMover) Move(ctx context.Context, artifacts ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Move indicates an expected call of Move.
func (mr *MockImageMoverMockRecorder) Move(ctx interface{}, artifacts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockChartDownloader is a mock of ChartDownloader interface.
type MockChartDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockChartDownloaderMockRecorder
}

// MockChartDownloaderMockRecorder is the mock recorder for MockChartDownloader.
type MockChartDownloaderMockRecorder struct {
	mock *MockChartDownloader
}

// NewMockChartDownloader creates a new mock instance.
func NewMockChartDownloader(ctrl *gomock.Controller) *MockChartDownloader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartDownloader) EXPECT() *MockChartDownloaderMockRecorder {
	_ = "STUB: not implemented"

	// Download mocks base method.
	return nil
}

func (m *MockChartDownloader) Download(ctx context.Context, artifacts ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Download indicates an expected call of Download.
func (mr *MockChartDownloaderMockRecorder) Download(ctx interface{}, artifacts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockManifestDownloader is a mock of ManifestDownloader interface.
type MockManifestDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockManifestDownloaderMockRecorder
}

// MockManifestDownloaderMockRecorder is the mock recorder for MockManifestDownloader.
type MockManifestDownloaderMockRecorder struct {
	mock *MockManifestDownloader
}

// NewMockManifestDownloader creates a new mock instance.
func NewMockManifestDownloader(ctrl *gomock.Controller) *MockManifestDownloader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestDownloader) EXPECT() *MockManifestDownloaderMockRecorder {
	_ = "STUB: not implemented"

	// Download mocks base method.
	return nil
}

func (m *MockManifestDownloader) Download(ctx context.Context, bundles *v1alpha1.Bundles) {
	_ = "STUB: not implemented"
	return
}

// Download indicates an expected call of Download.
func (mr *MockManifestDownloaderMockRecorder) Download(ctx, bundles interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPackager is a mock of Packager interface.
type MockPackager struct {
	ctrl     *gomock.Controller
	recorder *MockPackagerMockRecorder
}

// MockPackagerMockRecorder is the mock recorder for MockPackager.
type MockPackagerMockRecorder struct {
	mock *MockPackager
}

// NewMockPackager creates a new mock instance.
func NewMockPackager(ctrl *gomock.Controller) *MockPackager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackager) EXPECT() *MockPackagerMockRecorder {
	_ = "STUB: not implemented"

	// Package mocks base method.
	return nil
}

func (m *MockPackager) Package(folder, dstFile string) error { _ = "STUB: not implemented"; return nil }

// Package indicates an expected call of Package.
func (mr *MockPackagerMockRecorder) Package(folder, dstFile interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
