// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/eksctl-anywhere/cmd/internal/commands/artifacts/import_tools_image.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockUnPackager is a mock of UnPackager interface.
type MockUnPackager struct {
	ctrl     *gomock.Controller
	recorder *MockUnPackagerMockRecorder
}

// MockUnPackagerMockRecorder is the mock recorder for MockUnPackager.
type MockUnPackagerMockRecorder struct {
	mock *MockUnPackager
}

// NewMockUnPackager creates a new mock instance.
func NewMockUnPackager(ctrl *gomock.Controller) *MockUnPackager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnPackager) EXPECT() *MockUnPackagerMockRecorder {
	_ = "STUB: not implemented"

	// UnPackage mocks base method.
	return nil
}

func (m *MockUnPackager) UnPackage(orgFile, dstFolder string) error {
	_ = "STUB: not implemented"
	return nil
}

// UnPackage indicates an expected call of UnPackage.
func (mr *MockUnPackagerMockRecorder) UnPackage(orgFile, dstFolder interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
