// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/aws/ec2.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	gomock "github.com/golang/mock/gomock"
)

// MockEC2Client is a mock of EC2Client interface.
type MockEC2Client struct {
	ctrl     *gomock.Controller
	recorder *MockEC2ClientMockRecorder
}

// MockEC2ClientMockRecorder is the mock recorder for MockEC2Client.
type MockEC2ClientMockRecorder struct {
	mock *MockEC2Client
}

// NewMockEC2Client creates a new mock instance.
func NewMockEC2Client(ctrl *gomock.Controller) *MockEC2Client {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2Client) EXPECT() *MockEC2ClientMockRecorder {
	_ = "STUB: not implemented"

	// DescribeImages mocks base method.
	return nil
}

func (m *MockEC2Client) DescribeImages(ctx context.Context, params *ec2.DescribeImagesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeImagesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeImages indicates an expected call of DescribeImages.
func (mr *MockEC2ClientMockRecorder) DescribeImages(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeInstanceTypes mocks base method.
func (m *MockEC2Client) DescribeInstanceTypes(ctx context.Context, params *ec2.DescribeInstanceTypesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstanceTypesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeInstanceTypes indicates an expected call of DescribeInstanceTypes.
func (mr *MockEC2ClientMockRecorder) DescribeInstanceTypes(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeKeyPairs mocks base method.
func (m *MockEC2Client) DescribeKeyPairs(ctx context.Context, params *ec2.DescribeKeyPairsInput, optFns ...func(*ec2.Options)) (*ec2.DescribeKeyPairsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeKeyPairs indicates an expected call of DescribeKeyPairs.
func (mr *MockEC2ClientMockRecorder) DescribeKeyPairs(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ImportKeyPair mocks base method.
func (m *MockEC2Client) ImportKeyPair(ctx context.Context, params *ec2.ImportKeyPairInput, optFns ...func(*ec2.Options)) (*ec2.ImportKeyPairOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImportKeyPair indicates an expected call of ImportKeyPair.
func (mr *MockEC2ClientMockRecorder) ImportKeyPair(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
