// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/aws/imds.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	imds "github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
	gomock "github.com/golang/mock/gomock"
)

// MockIMDSClient is a mock of IMDSClient interface.
type MockIMDSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIMDSClientMockRecorder
}

// MockIMDSClientMockRecorder is the mock recorder for MockIMDSClient.
type MockIMDSClientMockRecorder struct {
	mock *MockIMDSClient
}

// NewMockIMDSClient creates a new mock instance.
func NewMockIMDSClient(ctrl *gomock.Controller) *MockIMDSClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMDSClient) EXPECT() *MockIMDSClientMockRecorder {
	_ = "STUB: not implemented"

	// GetMetadata mocks base method.
	return nil
}

func (m *MockIMDSClient) GetMetadata(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options)) (*imds.GetMetadataOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockIMDSClientMockRecorder) GetMetadata(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
