// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/aws/snowballdevice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	snowballdevice "github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice"
	gomock "github.com/golang/mock/gomock"
)

// MockSnowballDeviceClient is a mock of SnowballDeviceClient interface.
type MockSnowballDeviceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSnowballDeviceClientMockRecorder
}

// MockSnowballDeviceClientMockRecorder is the mock recorder for MockSnowballDeviceClient.
type MockSnowballDeviceClientMockRecorder struct {
	mock *MockSnowballDeviceClient
}

// NewMockSnowballDeviceClient creates a new mock instance.
func NewMockSnowballDeviceClient(ctrl *gomock.Controller) *MockSnowballDeviceClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnowballDeviceClient) EXPECT() *MockSnowballDeviceClientMockRecorder {
	_ = "STUB: not implemented"

	// DescribeDevice mocks base method.
	return nil
}

func (m *MockSnowballDeviceClient) DescribeDevice(ctx context.Context, params *snowballdevice.DescribeDeviceInput, optFns ...func(*snowballdevice.Options)) (*snowballdevice.DescribeDeviceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeDevice indicates an expected call of DescribeDevice.
func (mr *MockSnowballDeviceClientMockRecorder) DescribeDevice(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeDeviceSoftware mocks base method.
func (m *MockSnowballDeviceClient) DescribeDeviceSoftware(ctx context.Context, params *snowballdevice.DescribeDeviceSoftwareInput, optFns ...func(*snowballdevice.Options)) (*snowballdevice.DescribeDeviceSoftwareOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeDeviceSoftware indicates an expected call of DescribeDeviceSoftware.
func (mr *MockSnowballDeviceClientMockRecorder) DescribeDeviceSoftware(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
