// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/networkutils/netclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	net "net"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockNetClient is a mock of NetClient interface.
type MockNetClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetClientMockRecorder
}

// MockNetClientMockRecorder is the mock recorder for MockNetClient.
type MockNetClientMockRecorder struct {
	mock *MockNetClient
}

// NewMockNetClient creates a new mock instance.
func NewMockNetClient(ctrl *gomock.Controller) *MockNetClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetClient) EXPECT() *MockNetClientMockRecorder {
	_ = "STUB: not implemented"

	// DialTimeout mocks base method.
	return nil
}

func (m *MockNetClient) DialTimeout(network, address string, timeout time.Duration) (net.Conn, error) {
	_ = "STUB: not implemented"
	return *new(net.Conn), nil
}

// DialTimeout indicates an expected call of DialTimeout.
func (mr *MockNetClientMockRecorder) DialTimeout(network, address, timeout interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
