// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/controller/clusters/ipvalidator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockIPUniquenessValidator is a mock of IPUniquenessValidator interface.
type MockIPUniquenessValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIPUniquenessValidatorMockRecorder
}

// MockIPUniquenessValidatorMockRecorder is the mock recorder for MockIPUniquenessValidator.
type MockIPUniquenessValidatorMockRecorder struct {
	mock *MockIPUniquenessValidator
}

// NewMockIPUniquenessValidator creates a new mock instance.
func NewMockIPUniquenessValidator(ctrl *gomock.Controller) *MockIPUniquenessValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPUniquenessValidator) EXPECT() *MockIPUniquenessValidatorMockRecorder {
	_ = "STUB: not implemented"

	// ValidateControlPlaneIPUniqueness mocks base method.
	return nil
}

func (m *MockIPUniquenessValidator) ValidateControlPlaneIPUniqueness(cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateControlPlaneIPUniqueness indicates an expected call of ValidateControlPlaneIPUniqueness.
func (mr *MockIPUniquenessValidatorMockRecorder) ValidateControlPlaneIPUniqueness(cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
