// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/kubeconfig/kubeconfig.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"

	gomock "github.com/golang/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	_ = "STUB: not implemented"

	// WriteKubeconfig mocks base method.
	return nil
}

func (m *MockWriter) WriteKubeconfig(ctx context.Context, clusterName, kubeconfig string, w io.Writer) error {
	_ = "STUB: not implemented"
	return nil
}

// WriteKubeconfig indicates an expected call of WriteKubeconfig.
func (mr *MockWriterMockRecorder) WriteKubeconfig(ctx, clusterName, kubeconfig, w interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WriteKubeconfigContent mocks base method.
func (m *MockWriter) WriteKubeconfigContent(ctx context.Context, clusterName string, content []byte, w io.Writer) error {
	_ = "STUB: not implemented"
	return nil
}

// WriteKubeconfigContent indicates an expected call of WriteKubeconfigContent.
func (mr *MockWriterMockRecorder) WriteKubeconfigContent(ctx, clusterName, content, w interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
