// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/snow/aws.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	aws "github.com/aws/eks-anywhere/pkg/aws"
	gomock "github.com/golang/mock/gomock"
)

// MockAwsClient is a mock of AwsClient interface.
type MockAwsClient struct {
	ctrl     *gomock.Controller
	recorder *MockAwsClientMockRecorder
}

// MockAwsClientMockRecorder is the mock recorder for MockAwsClient.
type MockAwsClientMockRecorder struct {
	mock *MockAwsClient
}

// NewMockAwsClient creates a new mock instance.
func NewMockAwsClient(ctrl *gomock.Controller) *MockAwsClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAwsClient) EXPECT() *MockAwsClientMockRecorder {
	_ = "STUB: not implemented"

	// EC2ImageExists mocks base method.
	return nil
}

func (m *MockAwsClient) EC2ImageExists(ctx context.Context, imageID string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// EC2ImageExists indicates an expected call of EC2ImageExists.
func (mr *MockAwsClientMockRecorder) EC2ImageExists(ctx, imageID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EC2ImportKeyPair mocks base method.
func (m *MockAwsClient) EC2ImportKeyPair(ctx context.Context, keyName string, keyMaterial []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// EC2ImportKeyPair indicates an expected call of EC2ImportKeyPair.
func (mr *MockAwsClientMockRecorder) EC2ImportKeyPair(ctx, keyName, keyMaterial interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EC2InstanceTypes mocks base method.
func (m *MockAwsClient) EC2InstanceTypes(ctx context.Context) ([]aws.EC2InstanceType, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EC2InstanceTypes indicates an expected call of EC2InstanceTypes.
func (mr *MockAwsClientMockRecorder) EC2InstanceTypes(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EC2KeyNameExists mocks base method.
func (m *MockAwsClient) EC2KeyNameExists(ctx context.Context, keyName string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// EC2KeyNameExists indicates an expected call of EC2KeyNameExists.
func (mr *MockAwsClientMockRecorder) EC2KeyNameExists(ctx, keyName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsSnowballDeviceUnlocked mocks base method.
func (m *MockAwsClient) IsSnowballDeviceUnlocked(ctx context.Context) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsSnowballDeviceUnlocked indicates an expected call of IsSnowballDeviceUnlocked.
func (mr *MockAwsClientMockRecorder) IsSnowballDeviceUnlocked(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SnowballDeviceSoftwareVersion mocks base method.
func (m *MockAwsClient) SnowballDeviceSoftwareVersion(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// SnowballDeviceSoftwareVersion indicates an expected call of SnowballDeviceSoftwareVersion.
func (mr *MockAwsClientMockRecorder) SnowballDeviceSoftwareVersion(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockLocalIMDSClient is a mock of LocalIMDSClient interface.
type MockLocalIMDSClient struct {
	ctrl     *gomock.Controller
	recorder *MockLocalIMDSClientMockRecorder
}

// MockLocalIMDSClientMockRecorder is the mock recorder for MockLocalIMDSClient.
type MockLocalIMDSClientMockRecorder struct {
	mock *MockLocalIMDSClient
}

// NewMockLocalIMDSClient creates a new mock instance.
func NewMockLocalIMDSClient(ctrl *gomock.Controller) *MockLocalIMDSClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalIMDSClient) EXPECT() *MockLocalIMDSClientMockRecorder {
	_ = "STUB: not implemented"

	// EC2InstanceIP mocks base method.
	return nil
}

func (m *MockLocalIMDSClient) EC2InstanceIP(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// EC2InstanceIP indicates an expected call of EC2InstanceIP.
func (mr *MockLocalIMDSClientMockRecorder) EC2InstanceIP(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
