// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/snow/clientregistry.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	snow "github.com/aws/eks-anywhere/pkg/providers/snow"
	gomock "github.com/golang/mock/gomock"
)

// MockClientRegistry is a mock of ClientRegistry interface.
type MockClientRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockClientRegistryMockRecorder
}

// MockClientRegistryMockRecorder is the mock recorder for MockClientRegistry.
type MockClientRegistryMockRecorder struct {
	mock *MockClientRegistry
}

// NewMockClientRegistry creates a new mock instance.
func NewMockClientRegistry(ctrl *gomock.Controller) *MockClientRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRegistry) EXPECT() *MockClientRegistryMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockClientRegistry) Get(ctx context.Context) (snow.AwsClientMap, error) {
	_ = "STUB: not implemented"
	return *new(snow.AwsClientMap), nil
}

// Get indicates an expected call of Get.
func (mr *MockClientRegistryMockRecorder) Get(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
