// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/snow/snow.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	kubernetes "github.com/aws/eks-anywhere/pkg/clients/kubernetes"
	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockKubeUnAuthClient is a mock of KubeUnAuthClient interface.
type MockKubeUnAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeUnAuthClientMockRecorder
}

// MockKubeUnAuthClientMockRecorder is the mock recorder for MockKubeUnAuthClient.
type MockKubeUnAuthClientMockRecorder struct {
	mock *MockKubeUnAuthClient
}

// NewMockKubeUnAuthClient creates a new mock instance.
func NewMockKubeUnAuthClient(ctrl *gomock.Controller) *MockKubeUnAuthClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeUnAuthClient) EXPECT() *MockKubeUnAuthClientMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *MockKubeUnAuthClient) Apply(ctx context.Context, kubeconfig string, obj runtime.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Apply indicates an expected call of Apply.
func (mr *MockKubeUnAuthClientMockRecorder) Apply(ctx, kubeconfig, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// KubeconfigClient mocks base method.
func (m *MockKubeUnAuthClient) KubeconfigClient(kubeconfig string) kubernetes.Client {
	_ = "STUB: not implemented"
	return *new(kubernetes.Client)
}

// KubeconfigClient indicates an expected call of KubeconfigClient.
func (mr *MockKubeUnAuthClientMockRecorder) KubeconfigClient(kubeconfig interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
