// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/snow/defaults.go

// Package mocks is a generated GoMock package.
package mocks

import (
	filewriter "github.com/aws/eks-anywhere/pkg/filewriter"
	gomock "github.com/golang/mock/gomock"
)

// MockSshKeyGenerator is a mock of SshKeyGenerator interface.
type MockSshKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSshKeyGeneratorMockRecorder
}

// MockSshKeyGeneratorMockRecorder is the mock recorder for MockSshKeyGenerator.
type MockSshKeyGeneratorMockRecorder struct {
	mock *MockSshKeyGenerator
}

// NewMockSshKeyGenerator creates a new mock instance.
func NewMockSshKeyGenerator(ctrl *gomock.Controller) *MockSshKeyGenerator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSshKeyGenerator) EXPECT() *MockSshKeyGeneratorMockRecorder {
	_ = "STUB: not implemented"

	// GenerateSSHAuthKey mocks base method.
	return nil
}

func (m *MockSshKeyGenerator) GenerateSSHAuthKey(arg0 filewriter.FileWriter) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GenerateSSHAuthKey indicates an expected call of GenerateSSHAuthKey.
func (mr *MockSshKeyGeneratorMockRecorder) GenerateSSHAuthKey(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
