// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/git/providers/github (interfaces: GithubClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	git "github.com/aws/eks-anywhere/pkg/git"
	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/v35/github"
)

// MockGithubClient is a mock of GithubClient interface.
type MockGithubClient struct {
	ctrl     *gomock.Controller
	recorder *MockGithubClientMockRecorder
}

// MockGithubClientMockRecorder is the mock recorder for MockGithubClient.
type MockGithubClientMockRecorder struct {
	mock *MockGithubClient
}

// NewMockGithubClient creates a new mock instance.
func NewMockGithubClient(ctrl *gomock.Controller) *MockGithubClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubClient) EXPECT() *MockGithubClientMockRecorder {
	_ = "STUB: not implemented"

	// AddDeployKeyToRepo mocks base method.
	return nil
}

func (m *MockGithubClient) AddDeployKeyToRepo(arg0 context.Context, arg1 git.AddDeployKeyOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// AddDeployKeyToRepo indicates an expected call of AddDeployKeyToRepo.
func (mr *MockGithubClientMockRecorder) AddDeployKeyToRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AuthenticatedUser mocks base method.
func (m *MockGithubClient) AuthenticatedUser(arg0 context.Context) (*github.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AuthenticatedUser indicates an expected call of AuthenticatedUser.
func (mr *MockGithubClientMockRecorder) AuthenticatedUser(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckAccessTokenPermissions mocks base method.
func (m *MockGithubClient) CheckAccessTokenPermissions(arg0, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckAccessTokenPermissions indicates an expected call of CheckAccessTokenPermissions.
func (mr *MockGithubClientMockRecorder) CheckAccessTokenPermissions(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateRepo mocks base method.
func (m *MockGithubClient) CreateRepo(arg0 context.Context, arg1 git.CreateRepoOpts) (*git.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRepo indicates an expected call of CreateRepo.
func (mr *MockGithubClientMockRecorder) CreateRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRepo mocks base method.
func (m *MockGithubClient) DeleteRepo(arg0 context.Context, arg1 git.DeleteRepoOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRepo indicates an expected call of DeleteRepo.
func (mr *MockGithubClientMockRecorder) DeleteRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAccessTokenPermissions mocks base method.
func (m *MockGithubClient) GetAccessTokenPermissions(arg0 string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetAccessTokenPermissions indicates an expected call of GetAccessTokenPermissions.
func (mr *MockGithubClientMockRecorder) GetAccessTokenPermissions(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRepo mocks base method.
func (m *MockGithubClient) GetRepo(arg0 context.Context, arg1 git.GetRepoOpts) (*git.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockGithubClientMockRecorder) GetRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Organization mocks base method.
func (m *MockGithubClient) Organization(arg0 context.Context, arg1 string) (*github.Organization, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Organization indicates an expected call of Organization.
func (mr *MockGithubClientMockRecorder) Organization(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PathExists mocks base method.
func (m *MockGithubClient) PathExists(arg0 context.Context, arg1, arg2, arg3, arg4 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// PathExists indicates an expected call of PathExists.
func (mr *MockGithubClientMockRecorder) PathExists(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
