// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) GetSecretAccessKey(ctx context.Context, params *GetSecretAccessKeyInput, optFns ...func(*Options)) (*GetSecretAccessKeyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type GetSecretAccessKeyInput struct {

	// This member is required.
	AccessKeyId *string

	noSmithyDocumentSerde
}

type GetSecretAccessKeyOutput struct {

	// This member is required.
	AccessKeyId *string

	// This member is required.
	SecretAccessKey *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationGetSecretAccessKeyMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opGetSecretAccessKey(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
