// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) InstallUpdates(ctx context.Context, params *InstallUpdatesInput, optFns ...func(*Options)) (*InstallUpdatesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type InstallUpdatesInput struct {
	AuthenticationChallenge map[string]string

	ManifestSecret *string

	noSmithyDocumentSerde
}

type InstallUpdatesOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationInstallUpdatesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opInstallUpdates(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
