// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) SetFeatures(ctx context.Context, params *SetFeaturesInput, optFns ...func(*Options)) (*SetFeaturesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type SetFeaturesInput struct {
	RemoteManagementState types.FeatureStateInput

	// Deprecated: Remote monitoring is enabled by default and cannot be changed by
	// customers. Toggling this feature's state has been deprecated since 2023/09 and
	// will be removed after 2024/09.
	RemoteMonitoringState types.FeatureStateInput

	noSmithyDocumentSerde
}

type SetFeaturesOutput struct {
	RemoteManagementState types.FeatureState

	// Deprecated: Remote monitoring is enabled by default and cannot be changed by
	// customers. Toggling this feature's state has been deprecated since 2023/09 and
	// will be removed after 2024/09.
	RemoteMonitoringState types.FeatureState

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationSetFeaturesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opSetFeatures(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
