// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DeleteVirtualNetworkInterface(ctx context.Context, params *DeleteVirtualNetworkInterfaceInput, optFns ...func(*Options)) (*DeleteVirtualNetworkInterfaceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DeleteVirtualNetworkInterfaceInput struct {

	// This member is required.
	VirtualNetworkInterfaceArn *string

	noSmithyDocumentSerde
}

type DeleteVirtualNetworkInterfaceOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDeleteVirtualNetworkInterfaceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDeleteVirtualNetworkInterface(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
