// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeTimeSources(ctx context.Context, params *DescribeTimeSourcesInput, optFns ...func(*Options)) (*DescribeTimeSourcesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeTimeSourcesInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribeTimeSourcesOutput struct {

	// This member is required.
	Sources []types.TimeSourceStatus

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeTimeSourcesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDescribeTimeSources(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
