// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) CreateDirectNetworkInterface(ctx context.Context, params *CreateDirectNetworkInterfaceInput, optFns ...func(*Options)) (*CreateDirectNetworkInterfaceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type CreateDirectNetworkInterfaceInput struct {

	// This member is required.
	PhysicalNetworkInterfaceId *string

	InstanceId *string

	MacAddress *string

	VlanId *int32

	noSmithyDocumentSerde
}

type CreateDirectNetworkInterfaceOutput struct {

	// This member is required.
	DirectNetworkInterface *types.DirectNetworkInterface

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationCreateDirectNetworkInterfaceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opCreateDirectNetworkInterface(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
