// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) CreateAutoStartConfiguration(ctx context.Context, params *CreateAutoStartConfigurationInput, optFns ...func(*Options)) (*CreateAutoStartConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type CreateAutoStartConfigurationInput struct {

	// This member is required.
	IpAddressAssignment types.IpAddressAssignment

	// This member is required.
	LaunchTemplateId *string

	// This member is required.
	PhysicalConnectorType types.PhysicalConnectorType

	LaunchTemplateVersion *string

	StaticIpAddressConfiguration *types.StaticIpAddressConfiguration

	noSmithyDocumentSerde
}

type CreateAutoStartConfigurationOutput struct {
	AutoStartConfiguration *types.AutoStartConfiguration

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationCreateAutoStartConfigurationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opCreateAutoStartConfiguration(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
