// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) UpdateDirectNetworkInterface(ctx context.Context, params *UpdateDirectNetworkInterfaceInput, optFns ...func(*Options)) (*UpdateDirectNetworkInterfaceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type UpdateDirectNetworkInterfaceInput struct {

	// This member is required.
	DirectNetworkInterfaceArn *string

	Detach bool

	InstanceId *string

	MacAddress *string

	VlanId *int32

	noSmithyDocumentSerde
}

type UpdateDirectNetworkInterfaceOutput struct {

	// This member is required.
	DirectNetworkInterface *types.DirectNetworkInterface

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationUpdateDirectNetworkInterfaceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opUpdateDirectNetworkInterface(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
