// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) RebootDisplay(ctx context.Context, params *RebootDisplayInput, optFns ...func(*Options)) (*RebootDisplayOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type RebootDisplayInput struct {
	noSmithyDocumentSerde
}

type RebootDisplayOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationRebootDisplayMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opRebootDisplay(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
