// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeAutoUpdateStrategies(ctx context.Context, params *DescribeAutoUpdateStrategiesInput, optFns ...func(*Options)) (*DescribeAutoUpdateStrategiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeAutoUpdateStrategiesInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribeAutoUpdateStrategiesOutput struct {
	AutoUpdateStrategies []types.AutoUpdateStrategy

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeAutoUpdateStrategiesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// DescribeAutoUpdateStrategiesAPIClient is a client that implements the
// DescribeAutoUpdateStrategies operation.
type DescribeAutoUpdateStrategiesAPIClient interface {
	DescribeAutoUpdateStrategies(context.Context, *DescribeAutoUpdateStrategiesInput, ...func(*Options)) (*DescribeAutoUpdateStrategiesOutput, error)
}

var _ DescribeAutoUpdateStrategiesAPIClient = (*Client)(nil)

// DescribeAutoUpdateStrategiesPaginatorOptions is the paginator options for
// DescribeAutoUpdateStrategies
type DescribeAutoUpdateStrategiesPaginatorOptions struct {
	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// DescribeAutoUpdateStrategiesPaginator is a paginator for
// DescribeAutoUpdateStrategies
type DescribeAutoUpdateStrategiesPaginator struct {
	options   DescribeAutoUpdateStrategiesPaginatorOptions
	client    DescribeAutoUpdateStrategiesAPIClient
	params    *DescribeAutoUpdateStrategiesInput
	nextToken *string
	firstPage bool
}

// NewDescribeAutoUpdateStrategiesPaginator returns a new
// DescribeAutoUpdateStrategiesPaginator
func NewDescribeAutoUpdateStrategiesPaginator(client DescribeAutoUpdateStrategiesAPIClient, params *DescribeAutoUpdateStrategiesInput, optFns ...func(*DescribeAutoUpdateStrategiesPaginatorOptions)) *DescribeAutoUpdateStrategiesPaginator {
	_ = "STUB: not implemented"
	return nil
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *DescribeAutoUpdateStrategiesPaginator) HasMorePages() bool {
	_ = "STUB: not implemented"
	return false
}

// NextPage retrieves the next DescribeAutoUpdateStrategies page.
func (p *DescribeAutoUpdateStrategiesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeAutoUpdateStrategiesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func newServiceMetadataMiddleware_opDescribeAutoUpdateStrategies(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
