// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeDevice(ctx context.Context, params *DescribeDeviceInput, optFns ...func(*Options)) (*DescribeDeviceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeDeviceInput struct {
	noSmithyDocumentSerde
}

type DescribeDeviceOutput struct {

	// This member is required.
	DeviceId *string

	// This member is required.
	UnlockStatus *types.UnlockStatus

	ActiveNetworkInterface *types.NetworkInterface

	ClusterAssociation *types.ClusterAssociation

	DeviceCapacities []types.Capacity

	DeviceType *string

	PhysicalNetworkInterfaces []types.PhysicalNetworkInterface

	Tags []types.Tag

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeDeviceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDescribeDevice(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
