// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) ConfigureAutoUpdateStrategy(ctx context.Context, params *ConfigureAutoUpdateStrategyInput, optFns ...func(*Options)) (*ConfigureAutoUpdateStrategyOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ConfigureAutoUpdateStrategyInput struct {
	AutoCheck bool

	AutoCheckFrequency *string

	AutoDownload bool

	AutoDownloadFrequency *string

	AutoInstall bool

	AutoInstallFrequency *string

	AutoReboot bool

	noSmithyDocumentSerde
}

type ConfigureAutoUpdateStrategyOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationConfigureAutoUpdateStrategyMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opConfigureAutoUpdateStrategy(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
