// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) SetAlertSubscription(ctx context.Context, params *SetAlertSubscriptionInput, optFns ...func(*Options)) (*SetAlertSubscriptionOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type SetAlertSubscriptionInput struct {

	// This member is required.
	Name *string

	// This member is required.
	Namespace *string

	// This member is required.
	State types.AlertSubscriptionState

	Channels []types.AlertSubscriptionChannel

	noSmithyDocumentSerde
}

type SetAlertSubscriptionOutput struct {
	Name *string

	Namespace *string

	Subscription *types.AlertSubscription

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationSetAlertSubscriptionMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opSetAlertSubscription(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
