// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) UpdatePhysicalNetworkConfiguration(ctx context.Context, params *UpdatePhysicalNetworkConfigurationInput, optFns ...func(*Options)) (*UpdatePhysicalNetworkConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type UpdatePhysicalNetworkConfigurationInput struct {

	// This member is required.
	IpAddressAssignment types.IpAddressAssignment

	// This member is required.
	PhysicalNetworkInterfaceId *string

	StaticIpAddressConfiguration *types.StaticIpAddressConfiguration

	noSmithyDocumentSerde
}

type UpdatePhysicalNetworkConfigurationOutput struct {

	// This member is required.
	PhysicalNetworkInterface *types.PhysicalNetworkInterface

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationUpdatePhysicalNetworkConfigurationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opUpdatePhysicalNetworkConfiguration(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
