// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"
	"time"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) ListAlertHistory(ctx context.Context, params *ListAlertHistoryInput, optFns ...func(*Options)) (*ListAlertHistoryOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ListAlertHistoryInput struct {

	// This member is required.
	Name *string

	// This member is required.
	Namespace *string

	EndTime *time.Time

	MaxResults *int32

	NextToken *string

	ShowNotifications *bool

	StartTime *time.Time

	noSmithyDocumentSerde
}

type ListAlertHistoryOutput struct {
	History []types.AlertHistory

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationListAlertHistoryMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// ListAlertHistoryAPIClient is a client that implements the ListAlertHistory
// operation.
type ListAlertHistoryAPIClient interface {
	ListAlertHistory(context.Context, *ListAlertHistoryInput, ...func(*Options)) (*ListAlertHistoryOutput, error)
}

var _ ListAlertHistoryAPIClient = (*Client)(nil)

// ListAlertHistoryPaginatorOptions is the paginator options for ListAlertHistory
type ListAlertHistoryPaginatorOptions struct {
	Limit int32

	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// ListAlertHistoryPaginator is a paginator for ListAlertHistory
type ListAlertHistoryPaginator struct {
	options   ListAlertHistoryPaginatorOptions
	client    ListAlertHistoryAPIClient
	params    *ListAlertHistoryInput
	nextToken *string
	firstPage bool
}

// NewListAlertHistoryPaginator returns a new ListAlertHistoryPaginator
func NewListAlertHistoryPaginator(client ListAlertHistoryAPIClient, params *ListAlertHistoryInput, optFns ...func(*ListAlertHistoryPaginatorOptions)) *ListAlertHistoryPaginator {
	_ = "STUB: not implemented"
	return nil
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *ListAlertHistoryPaginator) HasMorePages() bool { _ = "STUB: not implemented"; return false }

// NextPage retrieves the next ListAlertHistory page.
func (p *ListAlertHistoryPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListAlertHistoryOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func newServiceMetadataMiddleware_opListAlertHistory(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
