// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DeleteAutoStartConfiguration(ctx context.Context, params *DeleteAutoStartConfigurationInput, optFns ...func(*Options)) (*DeleteAutoStartConfigurationOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DeleteAutoStartConfigurationInput struct {

	// This member is required.
	AutoStartConfigurationArn *string

	noSmithyDocumentSerde
}

type DeleteAutoStartConfigurationOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDeleteAutoStartConfigurationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDeleteAutoStartConfiguration(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
