// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeVirtualNetworkInterfaces(ctx context.Context, params *DescribeVirtualNetworkInterfacesInput, optFns ...func(*Options)) (*DescribeVirtualNetworkInterfacesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeVirtualNetworkInterfacesInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribeVirtualNetworkInterfacesOutput struct {

	// This member is required.
	VirtualNetworkInterfaces []types.VirtualNetworkInterface

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeVirtualNetworkInterfacesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// DescribeVirtualNetworkInterfacesAPIClient is a client that implements the
// DescribeVirtualNetworkInterfaces operation.
type DescribeVirtualNetworkInterfacesAPIClient interface {
	DescribeVirtualNetworkInterfaces(context.Context, *DescribeVirtualNetworkInterfacesInput, ...func(*Options)) (*DescribeVirtualNetworkInterfacesOutput, error)
}

var _ DescribeVirtualNetworkInterfacesAPIClient = (*Client)(nil)

// DescribeVirtualNetworkInterfacesPaginatorOptions is the paginator options for
// DescribeVirtualNetworkInterfaces
type DescribeVirtualNetworkInterfacesPaginatorOptions struct {
	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// DescribeVirtualNetworkInterfacesPaginator is a paginator for
// DescribeVirtualNetworkInterfaces
type DescribeVirtualNetworkInterfacesPaginator struct {
	options   DescribeVirtualNetworkInterfacesPaginatorOptions
	client    DescribeVirtualNetworkInterfacesAPIClient
	params    *DescribeVirtualNetworkInterfacesInput
	nextToken *string
	firstPage bool
}

// NewDescribeVirtualNetworkInterfacesPaginator returns a new
// DescribeVirtualNetworkInterfacesPaginator
func NewDescribeVirtualNetworkInterfacesPaginator(client DescribeVirtualNetworkInterfacesAPIClient, params *DescribeVirtualNetworkInterfacesInput, optFns ...func(*DescribeVirtualNetworkInterfacesPaginatorOptions)) *DescribeVirtualNetworkInterfacesPaginator {
	_ = "STUB: not implemented"
	return nil
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *DescribeVirtualNetworkInterfacesPaginator) HasMorePages() bool {
	_ = "STUB: not implemented"
	return false
}

// NextPage retrieves the next DescribeVirtualNetworkInterfaces page.
func (p *DescribeVirtualNetworkInterfacesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVirtualNetworkInterfacesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func newServiceMetadataMiddleware_opDescribeVirtualNetworkInterfaces(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
