// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) ListPciDevices(ctx context.Context, params *ListPciDevicesInput, optFns ...func(*Options)) (*ListPciDevicesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ListPciDevicesInput struct {
	InstanceIds []string

	MaxResults *int32

	NextToken *string

	Status types.PciDeviceStatus

	noSmithyDocumentSerde
}

type ListPciDevicesOutput struct {
	NextToken *string

	PciDevices []types.PciDevice

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationListPciDevicesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opListPciDevices(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
