// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeCluster(ctx context.Context, params *DescribeClusterInput, optFns ...func(*Options)) (*DescribeClusterOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeClusterInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribeClusterOutput struct {

	// This member is required.
	ClusterId *string

	Devices []types.Device

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeClusterMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDescribeCluster(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
