// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribePhysicalNetworkInterfaces(ctx context.Context, params *DescribePhysicalNetworkInterfacesInput, optFns ...func(*Options)) (*DescribePhysicalNetworkInterfacesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribePhysicalNetworkInterfacesInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribePhysicalNetworkInterfacesOutput struct {

	// This member is required.
	PhysicalNetworkInterfaces []types.PhysicalNetworkInterface

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribePhysicalNetworkInterfacesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// DescribePhysicalNetworkInterfacesAPIClient is a client that implements the
// DescribePhysicalNetworkInterfaces operation.
type DescribePhysicalNetworkInterfacesAPIClient interface {
	DescribePhysicalNetworkInterfaces(context.Context, *DescribePhysicalNetworkInterfacesInput, ...func(*Options)) (*DescribePhysicalNetworkInterfacesOutput, error)
}

var _ DescribePhysicalNetworkInterfacesAPIClient = (*Client)(nil)

// DescribePhysicalNetworkInterfacesPaginatorOptions is the paginator options for
// DescribePhysicalNetworkInterfaces
type DescribePhysicalNetworkInterfacesPaginatorOptions struct {
	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// DescribePhysicalNetworkInterfacesPaginator is a paginator for
// DescribePhysicalNetworkInterfaces
type DescribePhysicalNetworkInterfacesPaginator struct {
	options   DescribePhysicalNetworkInterfacesPaginatorOptions
	client    DescribePhysicalNetworkInterfacesAPIClient
	params    *DescribePhysicalNetworkInterfacesInput
	nextToken *string
	firstPage bool
}

// NewDescribePhysicalNetworkInterfacesPaginator returns a new
// DescribePhysicalNetworkInterfacesPaginator
func NewDescribePhysicalNetworkInterfacesPaginator(client DescribePhysicalNetworkInterfacesAPIClient, params *DescribePhysicalNetworkInterfacesInput, optFns ...func(*DescribePhysicalNetworkInterfacesPaginatorOptions)) *DescribePhysicalNetworkInterfacesPaginator {
	_ = "STUB: not implemented"
	return nil
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *DescribePhysicalNetworkInterfacesPaginator) HasMorePages() bool {
	_ = "STUB: not implemented"
	return false
}

// NextPage retrieves the next DescribePhysicalNetworkInterfaces page.
func (p *DescribePhysicalNetworkInterfacesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribePhysicalNetworkInterfacesOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func newServiceMetadataMiddleware_opDescribePhysicalNetworkInterfaces(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
