// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) AttachPciDevice(ctx context.Context, params *AttachPciDeviceInput, optFns ...func(*Options)) (*AttachPciDeviceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type AttachPciDeviceInput struct {

	// This member is required.
	InstanceId *string

	// This member is required.
	PciDeviceId *string

	noSmithyDocumentSerde
}

type AttachPciDeviceOutput struct {
	Device *types.PciDevice

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationAttachPciDeviceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opAttachPciDevice(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
