// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) StopService(ctx context.Context, params *StopServiceInput, optFns ...func(*Options)) (*StopServiceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type StopServiceInput struct {
	DeviceIpAddresses []string

	ServiceId *string

	Terminate bool

	noSmithyDocumentSerde
}

type StopServiceOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationStopServiceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opStopService(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
