// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) GetCertificate(ctx context.Context, params *GetCertificateInput, optFns ...func(*Options)) (*GetCertificateOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type GetCertificateInput struct {

	// This member is required.
	CertificateArn *string

	noSmithyDocumentSerde
}

type GetCertificateOutput struct {

	// This member is required.
	Certificate *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationGetCertificateMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opGetCertificate(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
