// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DescribeAutoStartConfigurations(ctx context.Context, params *DescribeAutoStartConfigurationsInput, optFns ...func(*Options)) (*DescribeAutoStartConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DescribeAutoStartConfigurationsInput struct {
	NextToken *string

	noSmithyDocumentSerde
}

type DescribeAutoStartConfigurationsOutput struct {
	AutoStartConfigurations []types.AutoStartConfigurationDetails

	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeAutoStartConfigurationsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// DescribeAutoStartConfigurationsAPIClient is a client that implements the
// DescribeAutoStartConfigurations operation.
type DescribeAutoStartConfigurationsAPIClient interface {
	DescribeAutoStartConfigurations(context.Context, *DescribeAutoStartConfigurationsInput, ...func(*Options)) (*DescribeAutoStartConfigurationsOutput, error)
}

var _ DescribeAutoStartConfigurationsAPIClient = (*Client)(nil)

// DescribeAutoStartConfigurationsPaginatorOptions is the paginator options for
// DescribeAutoStartConfigurations
type DescribeAutoStartConfigurationsPaginatorOptions struct {
	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// DescribeAutoStartConfigurationsPaginator is a paginator for
// DescribeAutoStartConfigurations
type DescribeAutoStartConfigurationsPaginator struct {
	options   DescribeAutoStartConfigurationsPaginatorOptions
	client    DescribeAutoStartConfigurationsAPIClient
	params    *DescribeAutoStartConfigurationsInput
	nextToken *string
	firstPage bool
}

// NewDescribeAutoStartConfigurationsPaginator returns a new
// DescribeAutoStartConfigurationsPaginator
func NewDescribeAutoStartConfigurationsPaginator(client DescribeAutoStartConfigurationsAPIClient, params *DescribeAutoStartConfigurationsInput, optFns ...func(*DescribeAutoStartConfigurationsPaginatorOptions)) *DescribeAutoStartConfigurationsPaginator {
	_ = "STUB: not implemented"
	return nil
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *DescribeAutoStartConfigurationsPaginator) HasMorePages() bool {
	_ = "STUB: not implemented"
	return false
}

// NextPage retrieves the next DescribeAutoStartConfigurations page.
func (p *DescribeAutoStartConfigurationsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeAutoStartConfigurationsOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func newServiceMetadataMiddleware_opDescribeAutoStartConfigurations(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
