// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) StartService(ctx context.Context, params *StartServiceInput, optFns ...func(*Options)) (*StartServiceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type StartServiceInput struct {
	Autostart bool

	DeviceIpAddresses []string

	ServiceConfiguration *types.ServiceConfiguration

	ServiceId *string

	VirtualNetworkInterfaceArns []string

	noSmithyDocumentSerde
}

type StartServiceOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationStartServiceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opStartService(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
