// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) ShutdownDevice(ctx context.Context, params *ShutdownDeviceInput, optFns ...func(*Options)) (*ShutdownDeviceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ShutdownDeviceInput struct {
	noSmithyDocumentSerde
}

type ShutdownDeviceOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationShutdownDeviceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opShutdownDevice(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
