// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/smithy-go/middleware"
)

func (c *Client) DeleteDirectNetworkInterface(ctx context.Context, params *DeleteDirectNetworkInterfaceInput, optFns ...func(*Options)) (*DeleteDirectNetworkInterfaceOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type DeleteDirectNetworkInterfaceInput struct {

	// This member is required.
	DirectNetworkInterfaceArn *string

	noSmithyDocumentSerde
}

type DeleteDirectNetworkInterfaceOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDeleteDirectNetworkInterfaceMiddlewares(stack *middleware.Stack, options Options) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func newServiceMetadataMiddleware_opDeleteDirectNetworkInterface(region string) *awsmiddleware.RegisterServiceMetadata {
	_ = "STUB: not implemented"
	return nil
}
