// Code generated by smithy-go-codegen DO NOT EDIT.

package snowballdevice

import (
	"context"

	"github.com/aws/eks-anywhere/internal/aws-sdk-go-v2/service/snowballdevice/types"
	smithyjson "github.com/aws/smithy-go/encoding/json"
	"github.com/aws/smithy-go/middleware"
)

type awsAwsjson11_serializeOpAttachPciDevice struct {
}

func (*awsAwsjson11_serializeOpAttachPciDevice) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpAttachPciDevice) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpCheckForUpdates struct {
}

func (*awsAwsjson11_serializeOpCheckForUpdates) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpCheckForUpdates) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpConfigureAutoUpdateStrategy struct {
}

func (*awsAwsjson11_serializeOpConfigureAutoUpdateStrategy) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpConfigureAutoUpdateStrategy) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpCreateAutoStartConfiguration struct {
}

func (*awsAwsjson11_serializeOpCreateAutoStartConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpCreateAutoStartConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpCreateDirectNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpCreateDirectNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpCreateDirectNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpCreateTags struct {
}

func (*awsAwsjson11_serializeOpCreateTags) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpCreateTags) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpCreateVirtualNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpCreateVirtualNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpCreateVirtualNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDeleteAutoStartConfiguration struct {
}

func (*awsAwsjson11_serializeOpDeleteAutoStartConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDeleteAutoStartConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDeleteCertificate struct {
}

func (*awsAwsjson11_serializeOpDeleteCertificate) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDeleteCertificate) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDeleteDirectNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpDeleteDirectNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDeleteDirectNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDeleteTags struct {
}

func (*awsAwsjson11_serializeOpDeleteTags) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDeleteTags) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDeleteVirtualNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpDeleteVirtualNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDeleteVirtualNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeAutoStartConfigurations struct {
}

func (*awsAwsjson11_serializeOpDescribeAutoStartConfigurations) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeAutoStartConfigurations) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeAutoUpdateStrategies struct {
}

func (*awsAwsjson11_serializeOpDescribeAutoUpdateStrategies) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeAutoUpdateStrategies) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeCluster struct {
}

func (*awsAwsjson11_serializeOpDescribeCluster) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDescribeCluster) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeDevice struct {
}

func (*awsAwsjson11_serializeOpDescribeDevice) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDescribeDevice) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeDeviceSoftware struct {
}

func (*awsAwsjson11_serializeOpDescribeDeviceSoftware) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeDeviceSoftware) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeDirectNetworkInterfaces struct {
}

func (*awsAwsjson11_serializeOpDescribeDirectNetworkInterfaces) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeDirectNetworkInterfaces) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeFeatures struct {
}

func (*awsAwsjson11_serializeOpDescribeFeatures) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDescribeFeatures) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribePhysicalNetworkInterfaces struct {
}

func (*awsAwsjson11_serializeOpDescribePhysicalNetworkInterfaces) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribePhysicalNetworkInterfaces) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeReturnShippingLabel struct {
}

func (*awsAwsjson11_serializeOpDescribeReturnShippingLabel) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeReturnShippingLabel) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeService struct {
}

func (*awsAwsjson11_serializeOpDescribeService) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDescribeService) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeTags struct {
}

func (*awsAwsjson11_serializeOpDescribeTags) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDescribeTags) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeTimeSources struct {
}

func (*awsAwsjson11_serializeOpDescribeTimeSources) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeTimeSources) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDescribeVirtualNetworkInterfaces struct {
}

func (*awsAwsjson11_serializeOpDescribeVirtualNetworkInterfaces) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpDescribeVirtualNetworkInterfaces) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDetachPciDevice struct {
}

func (*awsAwsjson11_serializeOpDetachPciDevice) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDetachPciDevice) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpDownloadUpdates struct {
}

func (*awsAwsjson11_serializeOpDownloadUpdates) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpDownloadUpdates) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpGetCertificate struct {
}

func (*awsAwsjson11_serializeOpGetCertificate) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpGetCertificate) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpGetNotificationConfiguration struct {
}

func (*awsAwsjson11_serializeOpGetNotificationConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpGetNotificationConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpGetReturnShippingLabel struct {
}

func (*awsAwsjson11_serializeOpGetReturnShippingLabel) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpGetReturnShippingLabel) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpGetSecretAccessKey struct {
}

func (*awsAwsjson11_serializeOpGetSecretAccessKey) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpGetSecretAccessKey) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpInstallUpdates struct {
}

func (*awsAwsjson11_serializeOpInstallUpdates) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpInstallUpdates) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListAccessKeys struct {
}

func (*awsAwsjson11_serializeOpListAccessKeys) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListAccessKeys) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListAlertHistory struct {
}

func (*awsAwsjson11_serializeOpListAlertHistory) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListAlertHistory) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListAlerts struct {
}

func (*awsAwsjson11_serializeOpListAlerts) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListAlerts) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListCertificates struct {
}

func (*awsAwsjson11_serializeOpListCertificates) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListCertificates) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListPciDevices struct {
}

func (*awsAwsjson11_serializeOpListPciDevices) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListPciDevices) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpListServices struct {
}

func (*awsAwsjson11_serializeOpListServices) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpListServices) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpPutNotificationConfiguration struct {
}

func (*awsAwsjson11_serializeOpPutNotificationConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpPutNotificationConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpRebootDevice struct {
}

func (*awsAwsjson11_serializeOpRebootDevice) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpRebootDevice) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpRebootDisplay struct {
}

func (*awsAwsjson11_serializeOpRebootDisplay) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpRebootDisplay) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpSetAlertSubscription struct {
}

func (*awsAwsjson11_serializeOpSetAlertSubscription) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpSetAlertSubscription) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpSetFeatures struct {
}

func (*awsAwsjson11_serializeOpSetFeatures) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpSetFeatures) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpShutdownDevice struct {
}

func (*awsAwsjson11_serializeOpShutdownDevice) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpShutdownDevice) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpStartService struct {
}

func (*awsAwsjson11_serializeOpStartService) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpStartService) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpStopService struct {
}

func (*awsAwsjson11_serializeOpStopService) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpStopService) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdateAutoStartConfiguration struct {
}

func (*awsAwsjson11_serializeOpUpdateAutoStartConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpUpdateAutoStartConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdateDirectNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpUpdateDirectNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpUpdateDirectNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdatePhysicalNetworkConfiguration struct {
}

func (*awsAwsjson11_serializeOpUpdatePhysicalNetworkConfiguration) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpUpdatePhysicalNetworkConfiguration) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdateService struct {
}

func (*awsAwsjson11_serializeOpUpdateService) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpUpdateService) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdateTimeServers struct {
}

func (*awsAwsjson11_serializeOpUpdateTimeServers) ID() string { _ = "STUB: not implemented"; return "" }

func (m *awsAwsjson11_serializeOpUpdateTimeServers) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

type awsAwsjson11_serializeOpUpdateVirtualNetworkInterface struct {
}

func (*awsAwsjson11_serializeOpUpdateVirtualNetworkInterface) ID() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *awsAwsjson11_serializeOpUpdateVirtualNetworkInterface) HandleSerialize(ctx context.Context, in middleware.SerializeInput, next middleware.SerializeHandler) (
	out middleware.SerializeOutput, metadata middleware.Metadata, err error,
) {
	_ = "STUB: not implemented"
	return *new(middleware.SerializeOutput), *new(middleware.Metadata), nil
}

func awsAwsjson11_serializeDocumentAlertSubscriptionChannelList(v []types.AlertSubscriptionChannel, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentAllowedHosts(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentArnList(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentIPv4AddressList(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentRecipients(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentResourceIdList(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentSensitiveStringStringMap(v map[string]string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentServiceConfiguration(v *types.ServiceConfiguration, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentStaticIpAddressConfiguration(v *types.StaticIpAddressConfiguration, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentTag(v *types.Tag, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentTagList(v []types.Tag, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeDocumentTimeServerList(v []string, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentAttachPciDeviceInput(v *AttachPciDeviceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentCheckForUpdatesInput(v *CheckForUpdatesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentConfigureAutoUpdateStrategyInput(v *ConfigureAutoUpdateStrategyInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentCreateAutoStartConfigurationInput(v *CreateAutoStartConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentCreateDirectNetworkInterfaceInput(v *CreateDirectNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentCreateTagsInput(v *CreateTagsInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentCreateVirtualNetworkInterfaceInput(v *CreateVirtualNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDeleteAutoStartConfigurationInput(v *DeleteAutoStartConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDeleteCertificateInput(v *DeleteCertificateInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDeleteDirectNetworkInterfaceInput(v *DeleteDirectNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDeleteTagsInput(v *DeleteTagsInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDeleteVirtualNetworkInterfaceInput(v *DeleteVirtualNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeAutoStartConfigurationsInput(v *DescribeAutoStartConfigurationsInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeAutoUpdateStrategiesInput(v *DescribeAutoUpdateStrategiesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeClusterInput(v *DescribeClusterInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeDeviceSoftwareInput(v *DescribeDeviceSoftwareInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeDirectNetworkInterfacesInput(v *DescribeDirectNetworkInterfacesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeFeaturesInput(v *DescribeFeaturesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribePhysicalNetworkInterfacesInput(v *DescribePhysicalNetworkInterfacesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeReturnShippingLabelInput(v *DescribeReturnShippingLabelInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeServiceInput(v *DescribeServiceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeTagsInput(v *DescribeTagsInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeTimeSourcesInput(v *DescribeTimeSourcesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDescribeVirtualNetworkInterfacesInput(v *DescribeVirtualNetworkInterfacesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDetachPciDeviceInput(v *DetachPciDeviceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentDownloadUpdatesInput(v *DownloadUpdatesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentGetCertificateInput(v *GetCertificateInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentGetNotificationConfigurationInput(v *GetNotificationConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentGetReturnShippingLabelInput(v *GetReturnShippingLabelInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentGetSecretAccessKeyInput(v *GetSecretAccessKeyInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentInstallUpdatesInput(v *InstallUpdatesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListAccessKeysInput(v *ListAccessKeysInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListAlertHistoryInput(v *ListAlertHistoryInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListAlertsInput(v *ListAlertsInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListCertificatesInput(v *ListCertificatesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListPciDevicesInput(v *ListPciDevicesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentListServicesInput(v *ListServicesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentPutNotificationConfigurationInput(v *PutNotificationConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentRebootDeviceInput(v *RebootDeviceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentRebootDisplayInput(v *RebootDisplayInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentSetAlertSubscriptionInput(v *SetAlertSubscriptionInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentSetFeaturesInput(v *SetFeaturesInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentShutdownDeviceInput(v *ShutdownDeviceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentStartServiceInput(v *StartServiceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentStopServiceInput(v *StopServiceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdateAutoStartConfigurationInput(v *UpdateAutoStartConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdateDirectNetworkInterfaceInput(v *UpdateDirectNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdatePhysicalNetworkConfigurationInput(v *UpdatePhysicalNetworkConfigurationInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdateServiceInput(v *UpdateServiceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdateTimeServersInput(v *UpdateTimeServersInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}

func awsAwsjson11_serializeOpDocumentUpdateVirtualNetworkInterfaceInput(v *UpdateVirtualNetworkInterfaceInput, value smithyjson.Value) error {
	_ = "STUB: not implemented"
	return nil
}
