// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/nutanix/kubectl.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	executables "github.com/aws/eks-anywhere/pkg/executables"
	types "github.com/aws/eks-anywhere/pkg/types"
	v1beta1 "github.com/aws/etcdadm-controller/api/v1beta1"
	gomock "github.com/golang/mock/gomock"
	v1beta2 "sigs.k8s.io/cluster-api/api/controlplane/kubeadm/v1beta2"
	v1beta20 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MockProviderKubectlClient is a mock of ProviderKubectlClient interface.
type MockProviderKubectlClient struct {
	ctrl     *gomock.Controller
	recorder *MockProviderKubectlClientMockRecorder
}

// MockProviderKubectlClientMockRecorder is the mock recorder for MockProviderKubectlClient.
type MockProviderKubectlClientMockRecorder struct {
	mock *MockProviderKubectlClient
}

// NewMockProviderKubectlClient creates a new mock instance.
func NewMockProviderKubectlClient(ctrl *gomock.Controller) *MockProviderKubectlClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderKubectlClient) EXPECT() *MockProviderKubectlClientMockRecorder {
	_ = "STUB: not implemented"

	// ApplyKubeSpecFromBytes mocks base method.
	return nil
}

func (m *MockProviderKubectlClient) ApplyKubeSpecFromBytes(ctx context.Context, cluster *types.Cluster, data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplyKubeSpecFromBytes indicates an expected call of ApplyKubeSpecFromBytes.
func (mr *MockProviderKubectlClientMockRecorder) ApplyKubeSpecFromBytes(ctx, cluster, data interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEksaNutanixDatacenterConfig mocks base method.
func (m *MockProviderKubectlClient) DeleteEksaNutanixDatacenterConfig(ctx context.Context, nutanixDatacenterConfigName, kubeconfigFile, namespace string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEksaNutanixDatacenterConfig indicates an expected call of DeleteEksaNutanixDatacenterConfig.
func (mr *MockProviderKubectlClientMockRecorder) DeleteEksaNutanixDatacenterConfig(ctx, nutanixDatacenterConfigName, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEksaNutanixMachineConfig mocks base method.
func (m *MockProviderKubectlClient) DeleteEksaNutanixMachineConfig(ctx context.Context, nutanixMachineConfigName, kubeconfigFile, namespace string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEksaNutanixMachineConfig indicates an expected call of DeleteEksaNutanixMachineConfig.
func (mr *MockProviderKubectlClientMockRecorder) DeleteEksaNutanixMachineConfig(ctx, nutanixMachineConfigName, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEksaCluster mocks base method.
func (m *MockProviderKubectlClient) GetEksaCluster(ctx context.Context, cluster *types.Cluster, clusterName string) (*v1alpha1.Cluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEksaCluster indicates an expected call of GetEksaCluster.
func (mr *MockProviderKubectlClientMockRecorder) GetEksaCluster(ctx, cluster, clusterName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEksaNutanixDatacenterConfig mocks base method.
func (m *MockProviderKubectlClient) GetEksaNutanixDatacenterConfig(ctx context.Context, nutanixDatacenterConfigName, kubeconfigFile, namespace string) (*v1alpha1.NutanixDatacenterConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEksaNutanixDatacenterConfig indicates an expected call of GetEksaNutanixDatacenterConfig.
func (mr *MockProviderKubectlClientMockRecorder) GetEksaNutanixDatacenterConfig(ctx, nutanixDatacenterConfigName, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEksaNutanixMachineConfig mocks base method.
func (m *MockProviderKubectlClient) GetEksaNutanixMachineConfig(ctx context.Context, nutanixMachineConfigName, kubeconfigFile, namespace string) (*v1alpha1.NutanixMachineConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEksaNutanixMachineConfig indicates an expected call of GetEksaNutanixMachineConfig.
func (mr *MockProviderKubectlClientMockRecorder) GetEksaNutanixMachineConfig(ctx, nutanixMachineConfigName, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEtcdadmCluster mocks base method.
func (m *MockProviderKubectlClient) GetEtcdadmCluster(ctx context.Context, cluster *types.Cluster, clusterName string, opts ...executables.KubectlOpt) (*v1beta1.EtcdadmCluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEtcdadmCluster indicates an expected call of GetEtcdadmCluster.
func (mr *MockProviderKubectlClientMockRecorder) GetEtcdadmCluster(ctx, cluster, clusterName interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetKubeadmControlPlane mocks base method.
func (m *MockProviderKubectlClient) GetKubeadmControlPlane(ctx context.Context, cluster *types.Cluster, clusterName string, opts ...executables.KubectlOpt) (*v1beta2.KubeadmControlPlane, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKubeadmControlPlane indicates an expected call of GetKubeadmControlPlane.
func (mr *MockProviderKubectlClientMockRecorder) GetKubeadmControlPlane(ctx, cluster, clusterName interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMachineDeployment mocks base method.
func (m *MockProviderKubectlClient) GetMachineDeployment(ctx context.Context, workerNodeGroupName string, opts ...executables.KubectlOpt) (*v1beta20.MachineDeployment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMachineDeployment indicates an expected call of GetMachineDeployment.
func (mr *MockProviderKubectlClientMockRecorder) GetMachineDeployment(ctx, workerNodeGroupName interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchNutanixDatacenterConfig mocks base method.
func (m *MockProviderKubectlClient) SearchNutanixDatacenterConfig(ctx context.Context, name, kubeconfigFile, namespace string) ([]*v1alpha1.NutanixDatacenterConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchNutanixDatacenterConfig indicates an expected call of SearchNutanixDatacenterConfig.
func (mr *MockProviderKubectlClientMockRecorder) SearchNutanixDatacenterConfig(ctx, name, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchNutanixMachineConfig mocks base method.
func (m *MockProviderKubectlClient) SearchNutanixMachineConfig(ctx context.Context, name, kubeconfigFile, namespace string) ([]*v1alpha1.NutanixMachineConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchNutanixMachineConfig indicates an expected call of SearchNutanixMachineConfig.
func (mr *MockProviderKubectlClientMockRecorder) SearchNutanixMachineConfig(ctx, name, kubeconfigFile, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetEksaControllerEnvVar mocks base method.
func (m *MockProviderKubectlClient) SetEksaControllerEnvVar(ctx context.Context, envVar, envVarVal, kubeconfig string) error {
	_ = "STUB: not implemented"
	return nil
}

// SetEksaControllerEnvVar indicates an expected call of SetEksaControllerEnvVar.
func (mr *MockProviderKubectlClientMockRecorder) SetEksaControllerEnvVar(ctx, envVar, envVarVal, kubeconfig interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation mocks base method.
func (m *MockProviderKubectlClient) UpdateAnnotation(ctx context.Context, resourceType, objectName string, annotations map[string]string, opts ...executables.KubectlOpt) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation indicates an expected call of UpdateAnnotation.
func (mr *MockProviderKubectlClientMockRecorder) UpdateAnnotation(ctx, resourceType, objectName, annotations interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
