// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/nutanix/validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockIPValidator is a mock of IPValidator interface.
type MockIPValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIPValidatorMockRecorder
}

// MockIPValidatorMockRecorder is the mock recorder for MockIPValidator.
type MockIPValidatorMockRecorder struct {
	mock *MockIPValidator
}

// NewMockIPValidator creates a new mock instance.
func NewMockIPValidator(ctrl *gomock.Controller) *MockIPValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPValidator) EXPECT() *MockIPValidatorMockRecorder {
	_ = "STUB: not implemented"

	// ValidateControlPlaneIPUniqueness mocks base method.
	return nil
}

func (m *MockIPValidator) ValidateControlPlaneIPUniqueness(cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateControlPlaneIPUniqueness indicates an expected call of ValidateControlPlaneIPUniqueness.
func (mr *MockIPValidatorMockRecorder) ValidateControlPlaneIPUniqueness(cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
