// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/task (interfaces: Task)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	task "github.com/aws/eks-anywhere/pkg/task"
	gomock "github.com/golang/mock/gomock"
)

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	_ = "STUB: not implemented"

	// Checkpoint mocks base method.
	return nil
}

func (m *MockTask) Checkpoint() *task.CompletedTask { _ = "STUB: not implemented"; return nil }

// Checkpoint indicates an expected call of Checkpoint.
func (mr *MockTaskMockRecorder) Checkpoint() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Name mocks base method.
func (m *MockTask) Name() string { _ = "STUB: not implemented"; return "" }

// Name indicates an expected call of Name.
func (mr *MockTaskMockRecorder) Name() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Restore mocks base method.
func (m *MockTask) Restore(arg0 context.Context, arg1 *task.CommandContext, arg2 *task.CompletedTask) (task.Task, error) {
	_ = "STUB: not implemented"
	return *new(task.Task), nil
}

// Restore indicates an expected call of Restore.
func (mr *MockTaskMockRecorder) Restore(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockTask) Run(arg0 context.Context, arg1 *task.CommandContext) task.Task {
	_ = "STUB: not implemented"
	return *new(task.Task)
}

// Run indicates an expected call of Run.
func (mr *MockTaskMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
