// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/vsphere/internal/templates/factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	executables "github.com/aws/eks-anywhere/pkg/executables"
	gomock "github.com/golang/mock/gomock"
)

// MockGovcClient is a mock of GovcClient interface.
type MockGovcClient struct {
	ctrl     *gomock.Controller
	recorder *MockGovcClientMockRecorder
}

// MockGovcClientMockRecorder is the mock recorder for MockGovcClient.
type MockGovcClientMockRecorder struct {
	mock *MockGovcClient
}

// NewMockGovcClient creates a new mock instance.
func NewMockGovcClient(ctrl *gomock.Controller) *MockGovcClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGovcClient) EXPECT() *MockGovcClientMockRecorder {
	_ = "STUB: not implemented"

	// AddTag mocks base method.
	return nil
}

func (m *MockGovcClient) AddTag(ctx context.Context, path, tag string) error {
	_ = "STUB: not implemented"
	return nil
}

// AddTag indicates an expected call of AddTag.
func (mr *MockGovcClientMockRecorder) AddTag(ctx, path, tag interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddUserToGroup mocks base method.
func (m *MockGovcClient) AddUserToGroup(ctx context.Context, name, username string) error {
	_ = "STUB: not implemented"
	return nil
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockGovcClientMockRecorder) AddUserToGroup(ctx, name, username interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateCategoryForVM mocks base method.
func (m *MockGovcClient) CreateCategoryForVM(ctx context.Context, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateCategoryForVM indicates an expected call of CreateCategoryForVM.
func (mr *MockGovcClientMockRecorder) CreateCategoryForVM(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateGroup mocks base method.
func (m *MockGovcClient) CreateGroup(ctx context.Context, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGovcClientMockRecorder) CreateGroup(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateLibrary mocks base method.
func (m *MockGovcClient) CreateLibrary(ctx context.Context, datastore, library string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateLibrary indicates an expected call of CreateLibrary.
func (mr *MockGovcClientMockRecorder) CreateLibrary(ctx, datastore, library interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateRole mocks base method.
func (m *MockGovcClient) CreateRole(ctx context.Context, name string, privileges []string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockGovcClientMockRecorder) CreateRole(ctx, name, privileges interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateTag mocks base method.
func (m *MockGovcClient) CreateTag(ctx context.Context, tag, category string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockGovcClientMockRecorder) CreateTag(ctx, tag, category interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockGovcClient) CreateUser(ctx context.Context, username, password string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGovcClientMockRecorder) CreateUser(ctx, username, password interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteLibraryElement mocks base method.
func (m *MockGovcClient) DeleteLibraryElement(ctx context.Context, element string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteLibraryElement indicates an expected call of DeleteLibraryElement.
func (mr *MockGovcClientMockRecorder) DeleteLibraryElement(ctx, element interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeployTemplateFromLibrary mocks base method.
func (m *MockGovcClient) DeployTemplateFromLibrary(ctx context.Context, templateDir, templateName, library, datacenter, datastore, network, resourcePool string, resizeBRDisk bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DeployTemplateFromLibrary indicates an expected call of DeployTemplateFromLibrary.
func (mr *MockGovcClientMockRecorder) DeployTemplateFromLibrary(ctx, templateDir, templateName, library, datacenter, datastore, network, resourcePool, resizeBRDisk interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLibraryElementContentVersion mocks base method.
func (m *MockGovcClient) GetLibraryElementContentVersion(ctx context.Context, element string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetLibraryElementContentVersion indicates an expected call of GetLibraryElementContentVersion.
func (mr *MockGovcClientMockRecorder) GetLibraryElementContentVersion(ctx, element interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupExists mocks base method.
func (m *MockGovcClient) GroupExists(ctx context.Context, name string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// GroupExists indicates an expected call of GroupExists.
func (mr *MockGovcClientMockRecorder) GroupExists(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ImportTemplate mocks base method.
func (m *MockGovcClient) ImportTemplate(ctx context.Context, library, ovaURL, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// ImportTemplate indicates an expected call of ImportTemplate.
func (mr *MockGovcClientMockRecorder) ImportTemplate(ctx, library, ovaURL, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LibraryElementExists mocks base method.
func (m *MockGovcClient) LibraryElementExists(ctx context.Context, library string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// LibraryElementExists indicates an expected call of LibraryElementExists.
func (mr *MockGovcClientMockRecorder) LibraryElementExists(ctx, library interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListCategories mocks base method.
func (m *MockGovcClient) ListCategories(ctx context.Context) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockGovcClientMockRecorder) ListCategories(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListTags mocks base method.
func (m *MockGovcClient) ListTags(ctx context.Context) ([]executables.Tag, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTags indicates an expected call of ListTags.
func (mr *MockGovcClientMockRecorder) ListTags(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RoleExists mocks base method.
func (m *MockGovcClient) RoleExists(ctx context.Context, name string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// RoleExists indicates an expected call of RoleExists.
func (mr *MockGovcClientMockRecorder) RoleExists(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchTemplate mocks base method.
func (m *MockGovcClient) SearchTemplate(ctx context.Context, datacenter, template string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// SearchTemplate indicates an expected call of SearchTemplate.
func (mr *MockGovcClientMockRecorder) SearchTemplate(ctx, datacenter, template interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetGroupRoleOnObject mocks base method.
func (m *MockGovcClient) SetGroupRoleOnObject(ctx context.Context, principal, role, object, domain string) error {
	_ = "STUB: not implemented"
	return nil
}

// SetGroupRoleOnObject indicates an expected call of SetGroupRoleOnObject.
func (mr *MockGovcClientMockRecorder) SetGroupRoleOnObject(ctx, principal, role, object, domain interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UserExists mocks base method.
func (m *MockGovcClient) UserExists(ctx context.Context, username string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// UserExists indicates an expected call of UserExists.
func (mr *MockGovcClientMockRecorder) UserExists(ctx, username interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
