// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/helm/factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	helm "github.com/aws/eks-anywhere/pkg/helm"
	gomock "github.com/golang/mock/gomock"
)

// MockClientBuilder is a mock of ClientBuilder interface.
type MockClientBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockClientBuilderMockRecorder
}

// MockClientBuilderMockRecorder is the mock recorder for MockClientBuilder.
type MockClientBuilderMockRecorder struct {
	mock *MockClientBuilder
}

// NewMockClientBuilder creates a new mock instance.
func NewMockClientBuilder(ctrl *gomock.Controller) *MockClientBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientBuilder) EXPECT() *MockClientBuilderMockRecorder {
	_ = "STUB: not implemented"

	// BuildHelm mocks base method.
	return nil
}

func (m *MockClientBuilder) BuildHelm(arg0 ...helm.Opt) helm.Client {
	_ = "STUB: not implemented"
	return *new(helm.Client)
}

// BuildHelm indicates an expected call of BuildHelm.
func (mr *MockClientBuilderMockRecorder) BuildHelm(arg0 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
