// Code generated by smithy-go-codegen DO NOT EDIT.

package types

type AlertLevel string

// Enum values for AlertLevel
const (
	AlertLevelInfo     AlertLevel = "INFO"
	AlertLevelWarning  AlertLevel = "WARNING"
	AlertLevelError    AlertLevel = "ERROR"
	AlertLevelCritical AlertLevel = "CRITICAL"
)

// Values returns all known values for AlertLevel. Note that this can be expanded
// in the future, and so it is only as up to date as the client. The ordering of
// this slice is not guaranteed to be stable across updates.
func (AlertLevel) Values() []AlertLevel { _ = "STUB: not implemented"; return nil }

type AlertNotificationStatus string

// Enum values for AlertNotificationStatus
const (
	AlertNotificationStatusSent    AlertNotificationStatus = "SENT"
	AlertNotificationStatusNotSent AlertNotificationStatus = "NOT_SENT"
	AlertNotificationStatusFailed  AlertNotificationStatus = "FAILED"
)

// Values returns all known values for AlertNotificationStatus. Note that this can
// be expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (AlertNotificationStatus) Values() []AlertNotificationStatus {
	_ = "STUB: not implemented"
	return nil
}

type AlertState string

// Enum values for AlertState
const (
	AlertStateActive   AlertState = "ACTIVE"
	AlertStateInactive AlertState = "INACTIVE"
)

// Values returns all known values for AlertState. Note that this can be expanded
// in the future, and so it is only as up to date as the client. The ordering of
// this slice is not guaranteed to be stable across updates.
func (AlertState) Values() []AlertState { _ = "STUB: not implemented"; return nil }

type AlertSubscriptionChannel string

// Enum values for AlertSubscriptionChannel
const (
	AlertSubscriptionChannelSmtp AlertSubscriptionChannel = "SMTP"
)

// Values returns all known values for AlertSubscriptionChannel. Note that this
// can be expanded in the future, and so it is only as up to date as the client.
// The ordering of this slice is not guaranteed to be stable across updates.
func (AlertSubscriptionChannel) Values() []AlertSubscriptionChannel {
	_ = "STUB: not implemented"
	return nil
}

type AlertSubscriptionState string

// Enum values for AlertSubscriptionState
const (
	AlertSubscriptionStateSubscribed   AlertSubscriptionState = "SUBSCRIBED"
	AlertSubscriptionStateUnsubscribed AlertSubscriptionState = "UNSUBSCRIBED"
)

// Values returns all known values for AlertSubscriptionState. Note that this can
// be expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (AlertSubscriptionState) Values() []AlertSubscriptionState {
	_ = "STUB: not implemented"
	return nil
}

type ClusterAssociationState string

// Enum values for ClusterAssociationState
const (
	ClusterAssociationStateAssociated     ClusterAssociationState = "ASSOCIATED"
	ClusterAssociationStateAssociating    ClusterAssociationState = "ASSOCIATING"
	ClusterAssociationStateDisassociated  ClusterAssociationState = "DISASSOCIATED"
	ClusterAssociationStateDisassociating ClusterAssociationState = "DISASSOCIATING"
)

// Values returns all known values for ClusterAssociationState. Note that this can
// be expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (ClusterAssociationState) Values() []ClusterAssociationState {
	_ = "STUB: not implemented"
	return nil
}

type DirectNetworkDriver string

// Enum values for DirectNetworkDriver
const (
	DirectNetworkDriverIxgbevf  DirectNetworkDriver = "ixgbevf"
	DirectNetworkDriverMlx5Core DirectNetworkDriver = "mlx5_core"
)

// Values returns all known values for DirectNetworkDriver. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (DirectNetworkDriver) Values() []DirectNetworkDriver { _ = "STUB: not implemented"; return nil }

type FeatureState string

// Enum values for FeatureState
const (
	FeatureStateInstalledAutostart FeatureState = "INSTALLED_AUTOSTART"
	FeatureStateInstalledOnly      FeatureState = "INSTALLED_ONLY"
	FeatureStateNotInstalled       FeatureState = "NOT_INSTALLED"
)

// Values returns all known values for FeatureState. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (FeatureState) Values() []FeatureState { _ = "STUB: not implemented"; return nil }

type FeatureStateInput string

// Enum values for FeatureStateInput
const (
	FeatureStateInputInstalledAutostart FeatureStateInput = "INSTALLED_AUTOSTART"
	FeatureStateInputInstalledOnly      FeatureStateInput = "INSTALLED_ONLY"
)

// Values returns all known values for FeatureStateInput. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (FeatureStateInput) Values() []FeatureStateInput { _ = "STUB: not implemented"; return nil }

type InstallState string

// Enum values for InstallState
const (
	InstallStateNa             InstallState = "NA"
	InstallStateDecrypting     InstallState = "DECRYPTING"
	InstallStateDecryptFailed  InstallState = "DECRYPT_FAILED"
	InstallStateDownloading    InstallState = "DOWNLOADING"
	InstallStateDownloadFailed InstallState = "DOWNLOAD_FAILED"
	InstallStateDownloaded     InstallState = "DOWNLOADED"
	InstallStateInstalling     InstallState = "INSTALLING"
	InstallStateRequireReboot  InstallState = "REQUIRE_REBOOT"
	InstallStateInstallFailed  InstallState = "INSTALL_FAILED"
)

// Values returns all known values for InstallState. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (InstallState) Values() []InstallState { _ = "STUB: not implemented"; return nil }

type IpAddressAssignment string

// Enum values for IpAddressAssignment
const (
	IpAddressAssignmentDhcp   IpAddressAssignment = "DHCP"
	IpAddressAssignmentStatic IpAddressAssignment = "STATIC"
)

// Values returns all known values for IpAddressAssignment. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (IpAddressAssignment) Values() []IpAddressAssignment { _ = "STUB: not implemented"; return nil }

type NetworkReachabilityState string

// Enum values for NetworkReachabilityState
const (
	NetworkReachabilityStateReachable   NetworkReachabilityState = "REACHABLE"
	NetworkReachabilityStateUnreachable NetworkReachabilityState = "UNREACHABLE"
)

// Values returns all known values for NetworkReachabilityState. Note that this
// can be expanded in the future, and so it is only as up to date as the client.
// The ordering of this slice is not guaranteed to be stable across updates.
func (NetworkReachabilityState) Values() []NetworkReachabilityState {
	_ = "STUB: not implemented"
	return nil
}

type NotificationType string

// Enum values for NotificationType
const (
	NotificationTypeSmtp NotificationType = "smtp"
)

// Values returns all known values for NotificationType. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (NotificationType) Values() []NotificationType { _ = "STUB: not implemented"; return nil }

type PciDeviceStatus string

// Enum values for PciDeviceStatus
const (
	PciDeviceStatusAttached  PciDeviceStatus = "ATTACHED"
	PciDeviceStatusAvailable PciDeviceStatus = "AVAILABLE"
	PciDeviceStatusFailed    PciDeviceStatus = "FAILED"
)

// Values returns all known values for PciDeviceStatus. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (PciDeviceStatus) Values() []PciDeviceStatus { _ = "STUB: not implemented"; return nil }

type PhysicalConnectorType string

// Enum values for PhysicalConnectorType
const (
	PhysicalConnectorTypeRj45    PhysicalConnectorType = "RJ45"
	PhysicalConnectorTypeRj452   PhysicalConnectorType = "RJ45_2"
	PhysicalConnectorTypeSfpPlus PhysicalConnectorType = "SFP_PLUS"
	PhysicalConnectorTypeQsfp    PhysicalConnectorType = "QSFP"
	PhysicalConnectorTypeWifi    PhysicalConnectorType = "WIFI"
)

// Values returns all known values for PhysicalConnectorType. Note that this can
// be expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (PhysicalConnectorType) Values() []PhysicalConnectorType {
	_ = "STUB: not implemented"
	return nil
}

type ServiceStatusState string

// Enum values for ServiceStatusState
const (
	ServiceStatusStateInactive     ServiceStatusState = "INACTIVE"
	ServiceStatusStateDeactivating ServiceStatusState = "DEACTIVATING"
	ServiceStatusStateDeactivated  ServiceStatusState = "DEACTIVATED"
	ServiceStatusStateActivating   ServiceStatusState = "ACTIVATING"
	ServiceStatusStateActive       ServiceStatusState = "ACTIVE"
	ServiceStatusStateDegraded     ServiceStatusState = "DEGRADED"
	ServiceStatusStateUpgrading    ServiceStatusState = "UPGRADING"
	ServiceStatusStateUnhealthy    ServiceStatusState = "UNHEALTHY"
)

// Values returns all known values for ServiceStatusState. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (ServiceStatusState) Values() []ServiceStatusState { _ = "STUB: not implemented"; return nil }

type ShippingLabelUpdateStatus string

// Enum values for ShippingLabelUpdateStatus
const (
	ShippingLabelUpdateStatusLabelStateUnavailable ShippingLabelUpdateStatus = "LABEL_STATE_UNAVAILABLE"
	ShippingLabelUpdateStatusLabelFound            ShippingLabelUpdateStatus = "LABEL_FOUND"
	ShippingLabelUpdateStatusLabelDownloaded       ShippingLabelUpdateStatus = "LABEL_DOWNLOADED"
	ShippingLabelUpdateStatusLabelDownloadFailed   ShippingLabelUpdateStatus = "LABEL_DOWNLOAD_FAILED"
	ShippingLabelUpdateStatusLabelDecrypted        ShippingLabelUpdateStatus = "LABEL_DECRYPTED"
	ShippingLabelUpdateStatusLabelDecryptedFailed  ShippingLabelUpdateStatus = "LABEL_DECRYPTED_FAILED"
	ShippingLabelUpdateStatusLabelCopyFailed       ShippingLabelUpdateStatus = "LABEL_COPY_FAILED"
	ShippingLabelUpdateStatusLabelReadyForDisplay  ShippingLabelUpdateStatus = "LABEL_READY_FOR_DISPLAY"
	ShippingLabelUpdateStatusDisplayRebooting      ShippingLabelUpdateStatus = "DISPLAY_REBOOTING"
	ShippingLabelUpdateStatusLabelDisplayTimeout   ShippingLabelUpdateStatus = "LABEL_DISPLAY_TIMEOUT"
	ShippingLabelUpdateStatusLabelDisplayIgnored   ShippingLabelUpdateStatus = "LABEL_DISPLAY_IGNORED"
	ShippingLabelUpdateStatusLabelOnDisplay        ShippingLabelUpdateStatus = "LABEL_ON_DISPLAY"
)

// Values returns all known values for ShippingLabelUpdateStatus. Note that this
// can be expanded in the future, and so it is only as up to date as the client.
// The ordering of this slice is not guaranteed to be stable across updates.
func (ShippingLabelUpdateStatus) Values() []ShippingLabelUpdateStatus {
	_ = "STUB: not implemented"
	return nil
}

type TimeSourceState string

// Enum values for TimeSourceState
const (
	TimeSourceStateCurrent      TimeSourceState = "CURRENT"
	TimeSourceStateCombined     TimeSourceState = "COMBINED"
	TimeSourceStateExcluded     TimeSourceState = "EXCLUDED"
	TimeSourceStateLost         TimeSourceState = "LOST"
	TimeSourceStateUnacceptable TimeSourceState = "UNACCEPTABLE"
)

// Values returns all known values for TimeSourceState. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (TimeSourceState) Values() []TimeSourceState { _ = "STUB: not implemented"; return nil }

type TimeSourceType string

// Enum values for TimeSourceType
const (
	TimeSourceTypeServer TimeSourceType = "SERVER"
	TimeSourceTypePeer   TimeSourceType = "PEER"
)

// Values returns all known values for TimeSourceType. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (TimeSourceType) Values() []TimeSourceType { _ = "STUB: not implemented"; return nil }

type UnlockStatusState string

// Enum values for UnlockStatusState
const (
	UnlockStatusStateLocked    UnlockStatusState = "LOCKED"
	UnlockStatusStateUnlocked  UnlockStatusState = "UNLOCKED"
	UnlockStatusStateUnlocking UnlockStatusState = "UNLOCKING"
)

// Values returns all known values for UnlockStatusState. Note that this can be
// expanded in the future, and so it is only as up to date as the client. The
// ordering of this slice is not guaranteed to be stable across updates.
func (UnlockStatusState) Values() []UnlockStatusState { _ = "STUB: not implemented"; return nil }
