// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithy "github.com/aws/smithy-go"
)

type DependencyException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *DependencyException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *DependencyException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *DependencyException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *DependencyException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type HardwarePlatformNotRecognizedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *HardwarePlatformNotRecognizedException) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *HardwarePlatformNotRecognizedException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *HardwarePlatformNotRecognizedException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *HardwarePlatformNotRecognizedException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type IncorrectDeviceManifestException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceManifestException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceManifestException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *IncorrectDeviceManifestException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceManifestException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type IncorrectDeviceStateException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceStateException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceStateException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceStateException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceStateException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type IncorrectDeviceUpdateStateException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceUpdateStateException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *IncorrectDeviceUpdateStateException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *IncorrectDeviceUpdateStateException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *IncorrectDeviceUpdateStateException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type InternalFailureException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InternalFailureException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *InternalFailureException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *InternalFailureException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *InternalFailureException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type InvalidPaginationTokenException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidPaginationTokenException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidPaginationTokenException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *InvalidPaginationTokenException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidPaginationTokenException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type InvalidParameterCombinationException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidParameterCombinationException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidParameterCombinationException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *InvalidParameterCombinationException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *InvalidParameterCombinationException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type InvalidParameterValueException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidParameterValueException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidParameterValueException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *InvalidParameterValueException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidParameterValueException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type InvalidRequestException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidRequestException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidRequestException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidRequestException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *InvalidRequestException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type MacAddressAlreadyInUseException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MacAddressAlreadyInUseException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *MacAddressAlreadyInUseException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *MacAddressAlreadyInUseException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *MacAddressAlreadyInUseException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type MaxDirectNetworkExceededException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MaxDirectNetworkExceededException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *MaxDirectNetworkExceededException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *MaxDirectNetworkExceededException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *MaxDirectNetworkExceededException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type MaxDirectNetworkOnInstanceException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MaxDirectNetworkOnInstanceException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *MaxDirectNetworkOnInstanceException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *MaxDirectNetworkOnInstanceException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *MaxDirectNetworkOnInstanceException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type MissingParameterException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MissingParameterException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *MissingParameterException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *MissingParameterException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *MissingParameterException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type NoCloudConnectionException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *NoCloudConnectionException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *NoCloudConnectionException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *NoCloudConnectionException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *NoCloudConnectionException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type NoDirectNetworkSupportException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *NoDirectNetworkSupportException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *NoDirectNetworkSupportException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *NoDirectNetworkSupportException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *NoDirectNetworkSupportException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type PciDeviceAlreadyAttachedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceAlreadyAttachedException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceAlreadyAttachedException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *PciDeviceAlreadyAttachedException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *PciDeviceAlreadyAttachedException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type PciDeviceMissingDataException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceMissingDataException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceMissingDataException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceMissingDataException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceMissingDataException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type PciDeviceNotFoundException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceNotFoundException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceNotFoundException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceNotFoundException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *PciDeviceNotFoundException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type PublicIpAlreadyAssociatedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PublicIpAlreadyAssociatedException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *PublicIpAlreadyAssociatedException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *PublicIpAlreadyAssociatedException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *PublicIpAlreadyAssociatedException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type ResourceNotFoundException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *ResourceNotFoundException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *ResourceNotFoundException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *ResourceNotFoundException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *ResourceNotFoundException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type ServiceAlreadyStartedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *ServiceAlreadyStartedException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *ServiceAlreadyStartedException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *ServiceAlreadyStartedException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *ServiceAlreadyStartedException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type TimeServiceSettingPersistenceException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *TimeServiceSettingPersistenceException) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *TimeServiceSettingPersistenceException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *TimeServiceSettingPersistenceException) ErrorCode() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *TimeServiceSettingPersistenceException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type TimeServiceUnavailableException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *TimeServiceUnavailableException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *TimeServiceUnavailableException) ErrorMessage() string {
	_ = "STUB: not implemented"
	return ""
}

func (e *TimeServiceUnavailableException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *TimeServiceUnavailableException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type UnsupportedFeatureException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *UnsupportedFeatureException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedFeatureException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedFeatureException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedFeatureException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}

type UnsupportedOperationException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *UnsupportedOperationException) Error() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedOperationException) ErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedOperationException) ErrorCode() string { _ = "STUB: not implemented"; return "" }

func (e *UnsupportedOperationException) ErrorFault() smithy.ErrorFault {
	_ = "STUB: not implemented"
	return *new(smithy.ErrorFault)
}
