// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/registry/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	registry "github.com/aws/eks-anywhere/pkg/registry"
	gomock "github.com/golang/mock/gomock"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	registry0 "oras.land/oras-go/v2/registry"
)

// MockStorageClient is a mock of StorageClient interface.
type MockStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClientMockRecorder
}

// MockStorageClientMockRecorder is the mock recorder for MockStorageClient.
type MockStorageClientMockRecorder struct {
	mock *MockStorageClient
}

// NewMockStorageClient creates a new mock instance.
func NewMockStorageClient(ctrl *gomock.Controller) *MockStorageClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClient) EXPECT() *MockStorageClientMockRecorder {
	_ = "STUB: not implemented"

	// CopyGraph mocks base method.
	return nil
}

func (m *MockStorageClient) CopyGraph(ctx context.Context, srcStorage registry0.Repository, srcRef string, dstStorage registry0.Repository, dstRef string) (v1.Descriptor, error) {
	_ = "STUB: not implemented"
	return *new(v1.Descriptor), nil
}

// CopyGraph indicates an expected call of CopyGraph.
func (mr *MockStorageClientMockRecorder) CopyGraph(ctx, srcStorage, srcRef, dstStorage, dstRef interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Destination mocks base method.
func (m *MockStorageClient) Destination(image registry.Artifact) string {
	_ = "STUB: not implemented"
	return ""
}

// Destination indicates an expected call of Destination.
func (mr *MockStorageClientMockRecorder) Destination(image interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FetchBlob mocks base method.
func (m *MockStorageClient) FetchBlob(ctx context.Context, srcStorage registry0.Repository, descriptor v1.Descriptor) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FetchBlob indicates an expected call of FetchBlob.
func (mr *MockStorageClientMockRecorder) FetchBlob(ctx, srcStorage, descriptor interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FetchBytes mocks base method.
func (m *MockStorageClient) FetchBytes(ctx context.Context, srcStorage registry0.Repository, artifact registry.Artifact) (v1.Descriptor, []byte, error) {
	_ = "STUB: not implemented"
	return *new(v1.Descriptor), nil, nil
}

// FetchBytes indicates an expected call of FetchBytes.
func (mr *MockStorageClientMockRecorder) FetchBytes(ctx, srcStorage, artifact interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStorage mocks base method.
func (m *MockStorageClient) GetStorage(ctx context.Context, image registry.Artifact) (registry0.Repository, error) {
	_ = "STUB: not implemented"
	return *new(registry0.Repository), nil
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockStorageClientMockRecorder) GetStorage(ctx, image interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockStorageClient) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockStorageClientMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Resolve mocks base method.
func (m *MockStorageClient) Resolve(ctx context.Context, srcStorage registry0.Repository, versionedImage string) (v1.Descriptor, error) {
	_ = "STUB: not implemented"
	return *new(v1.Descriptor), nil
}

// Resolve indicates an expected call of Resolve.
func (mr *MockStorageClientMockRecorder) Resolve(ctx, srcStorage, versionedImage interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetProject mocks base method.
func (m *MockStorageClient) SetProject(project string) { _ = "STUB: not implemented"; return }

// SetProject indicates an expected call of SetProject.
func (mr *MockStorageClientMockRecorder) SetProject(project interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Tag mocks base method.
func (m *MockStorageClient) Tag(ctx context.Context, dstStorage registry0.Repository, desc v1.Descriptor, tag string) error {
	_ = "STUB: not implemented"
	return nil
}

// Tag indicates an expected call of Tag.
func (mr *MockStorageClientMockRecorder) Tag(ctx, dstStorage, desc, tag interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
