// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/providers/vsphere/setupuser (interfaces: GovcClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
)

// MockGovcClient is a mock of GovcClient interface.
type MockGovcClient struct {
	ctrl     *gomock.Controller
	recorder *MockGovcClientMockRecorder
}

// MockGovcClientMockRecorder is the mock recorder for MockGovcClient.
type MockGovcClientMockRecorder struct {
	mock *MockGovcClient
}

// NewMockGovcClient creates a new mock instance.
func NewMockGovcClient(ctrl *gomock.Controller) *MockGovcClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGovcClient) EXPECT() *MockGovcClientMockRecorder {
	_ = "STUB: not implemented"

	// AddUserToGroup mocks base method.
	return nil
}

func (m *MockGovcClient) AddUserToGroup(arg0 context.Context, arg1, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockGovcClientMockRecorder) AddUserToGroup(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateGroup mocks base method.
func (m *MockGovcClient) CreateGroup(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGovcClientMockRecorder) CreateGroup(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateRole mocks base method.
func (m *MockGovcClient) CreateRole(arg0 context.Context, arg1 string, arg2 []string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockGovcClientMockRecorder) CreateRole(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockGovcClient) CreateUser(arg0 context.Context, arg1, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGovcClientMockRecorder) CreateUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupExists mocks base method.
func (m *MockGovcClient) GroupExists(arg0 context.Context, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// GroupExists indicates an expected call of GroupExists.
func (mr *MockGovcClientMockRecorder) GroupExists(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RoleExists mocks base method.
func (m *MockGovcClient) RoleExists(arg0 context.Context, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// RoleExists indicates an expected call of RoleExists.
func (mr *MockGovcClientMockRecorder) RoleExists(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetGroupRoleOnObject mocks base method.
func (m *MockGovcClient) SetGroupRoleOnObject(arg0 context.Context, arg1, arg2, arg3, arg4 string) error {
	_ = "STUB: not implemented"
	return nil
}

// SetGroupRoleOnObject indicates an expected call of SetGroupRoleOnObject.
func (mr *MockGovcClientMockRecorder) SetGroupRoleOnObject(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UserExists mocks base method.
func (m *MockGovcClient) UserExists(arg0 context.Context, arg1 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// UserExists indicates an expected call of UserExists.
func (mr *MockGovcClientMockRecorder) UserExists(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
