// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/networking/cilium/templater.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	helm "github.com/aws/eks-anywhere/pkg/helm"
	gomock "github.com/golang/mock/gomock"
)

// MockHelmClientFactory is a mock of HelmClientFactory interface.
type MockHelmClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockHelmClientFactoryMockRecorder
}

// MockHelmClientFactoryMockRecorder is the mock recorder for MockHelmClientFactory.
type MockHelmClientFactoryMockRecorder struct {
	mock *MockHelmClientFactory
}

// NewMockHelmClientFactory creates a new mock instance.
func NewMockHelmClientFactory(ctrl *gomock.Controller) *MockHelmClientFactory {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelmClientFactory) EXPECT() *MockHelmClientFactoryMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockHelmClientFactory) Get(ctx context.Context, clus *v1alpha1.Cluster) (helm.Client, error) {
	_ = "STUB: not implemented"
	return *new(helm.Client), nil
}

// Get indicates an expected call of Get.
func (mr *MockHelmClientFactoryMockRecorder) Get(ctx, clus interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
