// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/curatedpackages/packagecontrollerclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockClientBuilder is a mock of ClientBuilder interface.
type MockClientBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockClientBuilderMockRecorder
}

// MockClientBuilderMockRecorder is the mock recorder for MockClientBuilder.
type MockClientBuilderMockRecorder struct {
	mock *MockClientBuilder
}

// NewMockClientBuilder creates a new mock instance.
func NewMockClientBuilder(ctrl *gomock.Controller) *MockClientBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientBuilder) EXPECT() *MockClientBuilderMockRecorder {
	_ = "STUB: not implemented"

	// GetClient mocks base method.
	return nil
}

func (m *MockClientBuilder) GetClient(arg0 context.Context, arg1 types.NamespacedName) (client.Client, error) {
	_ = "STUB: not implemented"
	return *new(client.Client), nil
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientBuilderMockRecorder) GetClient(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockChartInstaller is a mock of ChartInstaller interface.
type MockChartInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockChartInstallerMockRecorder
}

// MockChartInstallerMockRecorder is the mock recorder for MockChartInstaller.
type MockChartInstallerMockRecorder struct {
	mock *MockChartInstaller
}

// NewMockChartInstaller creates a new mock instance.
func NewMockChartInstaller(ctrl *gomock.Controller) *MockChartInstaller {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartInstaller) EXPECT() *MockChartInstallerMockRecorder {
	_ = "STUB: not implemented"

	// InstallChart mocks base method.
	return nil
}

func (m *MockChartInstaller) InstallChart(ctx context.Context, chart, ociURI, version, kubeconfigFilePath, namespace, valueFilePath string, skipCRDs bool, values []string) error {
	_ = "STUB: not implemented"
	return nil
}

// InstallChart indicates an expected call of InstallChart.
func (mr *MockChartInstallerMockRecorder) InstallChart(ctx, chart, ociURI, version, kubeconfigFilePath, namespace, valueFilePath, skipCRDs, values interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockChartUninstaller is a mock of ChartUninstaller interface.
type MockChartUninstaller struct {
	ctrl     *gomock.Controller
	recorder *MockChartUninstallerMockRecorder
}

// MockChartUninstallerMockRecorder is the mock recorder for MockChartUninstaller.
type MockChartUninstallerMockRecorder struct {
	mock *MockChartUninstaller
}

// NewMockChartUninstaller creates a new mock instance.
func NewMockChartUninstaller(ctrl *gomock.Controller) *MockChartUninstaller {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartUninstaller) EXPECT() *MockChartUninstallerMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockChartUninstaller) Delete(ctx context.Context, kubeconfigFilePath, installName, namespace string) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockChartUninstallerMockRecorder) Delete(ctx, kubeconfigFilePath, installName, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockChartManager is a mock of ChartManager interface.
type MockChartManager struct {
	ctrl     *gomock.Controller
	recorder *MockChartManagerMockRecorder
}

// MockChartManagerMockRecorder is the mock recorder for MockChartManager.
type MockChartManagerMockRecorder struct {
	mock *MockChartManager
}

// NewMockChartManager creates a new mock instance.
func NewMockChartManager(ctrl *gomock.Controller) *MockChartManager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartManager) EXPECT() *MockChartManagerMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockChartManager) Delete(ctx context.Context, kubeconfigFilePath, installName, namespace string) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockChartManagerMockRecorder) Delete(ctx, kubeconfigFilePath, installName, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InstallChart mocks base method.
func (m *MockChartManager) InstallChart(ctx context.Context, chart, ociURI, version, kubeconfigFilePath, namespace, valueFilePath string, skipCRDs bool, values []string) error {
	_ = "STUB: not implemented"
	return nil
}

// InstallChart indicates an expected call of InstallChart.
func (mr *MockChartManagerMockRecorder) InstallChart(ctx, chart, ociURI, version, kubeconfigFilePath, namespace, valueFilePath, skipCRDs, values interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegistryLogin mocks base method.
func (m *MockChartManager) RegistryLogin(ctx context.Context, registry, username, password string) error {
	_ = "STUB: not implemented"
	return nil
}

// RegistryLogin indicates an expected call of RegistryLogin.
func (mr *MockChartManagerMockRecorder) RegistryLogin(ctx, registry, username, password interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubeDeleter is a mock of KubeDeleter interface.
type MockKubeDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockKubeDeleterMockRecorder
}

// MockKubeDeleterMockRecorder is the mock recorder for MockKubeDeleter.
type MockKubeDeleterMockRecorder struct {
	mock *MockKubeDeleter
}

// NewMockKubeDeleter creates a new mock instance.
func NewMockKubeDeleter(ctrl *gomock.Controller) *MockKubeDeleter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeDeleter) EXPECT() *MockKubeDeleterMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockKubeDeleter) Delete(arg0 context.Context, arg1 client.Object, arg2 ...client.DeleteOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockKubeDeleterMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
