// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/curatedpackages/kubectlrunner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	context "context"

	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockKubectlRunner is a mock of KubectlRunner interface.
type MockKubectlRunner struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlRunnerMockRecorder
}

// MockKubectlRunnerMockRecorder is the mock recorder for MockKubectlRunner.
type MockKubectlRunnerMockRecorder struct {
	mock *MockKubectlRunner
}

// NewMockKubectlRunner creates a new mock instance.
func NewMockKubectlRunner(ctrl *gomock.Controller) *MockKubectlRunner {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectlRunner) EXPECT() *MockKubectlRunnerMockRecorder {
	_ = "STUB: not implemented"

	// ExecuteCommand mocks base method.
	return nil
}

func (m *MockKubectlRunner) ExecuteCommand(ctx context.Context, opts ...string) (bytes.Buffer, error) {
	_ = "STUB: not implemented"
	return *new(bytes.Buffer), nil
}

// ExecuteCommand indicates an expected call of ExecuteCommand.
func (mr *MockKubectlRunnerMockRecorder) ExecuteCommand(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteFromYaml mocks base method.
func (m *MockKubectlRunner) ExecuteFromYaml(ctx context.Context, yaml []byte, opts ...string) (bytes.Buffer, error) {
	_ = "STUB: not implemented"
	return *new(bytes.Buffer), nil
}

// ExecuteFromYaml indicates an expected call of ExecuteFromYaml.
func (mr *MockKubectlRunnerMockRecorder) ExecuteFromYaml(ctx, yaml interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *MockKubectlRunner) GetObject(ctx context.Context, resourceType, name, namespece, kubeconfig string, obj runtime.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// GetObject indicates an expected call of GetObject.
func (mr *MockKubectlRunnerMockRecorder) GetObject(ctx, resourceType, name, namespece, kubeconfig, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasResource mocks base method.
func (m *MockKubectlRunner) HasResource(ctx context.Context, resourceType, name, kubeconfig, namespace string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// HasResource indicates an expected call of HasResource.
func (mr *MockKubectlRunnerMockRecorder) HasResource(ctx, resourceType, name, kubeconfig, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
