// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/controller-runtime/pkg/client (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	meta "k8s.io/apimachinery/pkg/api/meta"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockKubeClient is a mock of Client interface.
type MockKubeClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeClientMockRecorder
}

// MockKubeClientMockRecorder is the mock recorder for MockKubeClient.
type MockKubeClientMockRecorder struct {
	mock *MockKubeClient
}

// NewMockKubeClient creates a new mock instance.
func NewMockKubeClient(ctrl *gomock.Controller) *MockKubeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeClient) EXPECT() *MockKubeClientMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *MockKubeClient) Apply(arg0 context.Context, arg1 runtime.ApplyConfiguration, arg2 ...client.ApplyOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Apply indicates an expected call of Apply.
func (mr *MockKubeClientMockRecorder) Apply(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockKubeClient) Create(arg0 context.Context, arg1 client.Object, arg2 ...client.CreateOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Create indicates an expected call of Create.
func (mr *MockKubeClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockKubeClient) Delete(arg0 context.Context, arg1 client.Object, arg2 ...client.DeleteOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockKubeClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf mocks base method.
func (m *MockKubeClient) DeleteAllOf(arg0 context.Context, arg1 client.Object, arg2 ...client.DeleteAllOfOption) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf indicates an expected call of DeleteAllOf.
func (mr *MockKubeClientMockRecorder) DeleteAllOf(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockKubeClient) Get(arg0 context.Context, arg1 types.NamespacedName, arg2 client.Object, arg3 ...client.GetOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockKubeClientMockRecorder) Get(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupVersionKindFor mocks base method.
func (m *MockKubeClient) GroupVersionKindFor(arg0 runtime.Object) (schema.GroupVersionKind, error) {
	_ = "STUB: not implemented"
	return *new(schema.GroupVersionKind), nil
}

// GroupVersionKindFor indicates an expected call of GroupVersionKindFor.
func (mr *MockKubeClientMockRecorder) GroupVersionKindFor(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsObjectNamespaced mocks base method.
func (m *MockKubeClient) IsObjectNamespaced(arg0 runtime.Object) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsObjectNamespaced indicates an expected call of IsObjectNamespaced.
func (mr *MockKubeClientMockRecorder) IsObjectNamespaced(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockKubeClient) List(arg0 context.Context, arg1 client.ObjectList, arg2 ...client.ListOption) error {
	_ = "STUB: not implemented"
	return nil
}

// List indicates an expected call of List.
func (mr *MockKubeClientMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Patch mocks base method.
func (m *MockKubeClient) Patch(arg0 context.Context, arg1 client.Object, arg2 client.Patch, arg3 ...client.PatchOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch indicates an expected call of Patch.
func (mr *MockKubeClientMockRecorder) Patch(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RESTMapper mocks base method.
func (m *MockKubeClient) RESTMapper() meta.RESTMapper {
	_ = "STUB: not implemented"
	return *new(meta.RESTMapper)
}

// RESTMapper indicates an expected call of RESTMapper.
func (mr *MockKubeClientMockRecorder) RESTMapper() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Scheme mocks base method.
func (m *MockKubeClient) Scheme() *runtime.Scheme { _ = "STUB: not implemented"; return nil }

// Scheme indicates an expected call of Scheme.
func (mr *MockKubeClientMockRecorder) Scheme() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Status mocks base method.
func (m *MockKubeClient) Status() client.SubResourceWriter {
	_ = "STUB: not implemented"
	return *new(client.SubResourceWriter)
}

// Status indicates an expected call of Status.
func (mr *MockKubeClientMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SubResource mocks base method.
func (m *MockKubeClient) SubResource(arg0 string) client.SubResourceClient {
	_ = "STUB: not implemented"
	return *new(client.SubResourceClient)
}

// SubResource indicates an expected call of SubResource.
func (mr *MockKubeClientMockRecorder) SubResource(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockKubeClient) Update(arg0 context.Context, arg1 client.Object, arg2 ...client.UpdateOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Update indicates an expected call of Update.
func (mr *MockKubeClientMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
