// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/curatedpackages/packageinstaller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
)

// MockPackageController is a mock of PackageController interface.
type MockPackageController struct {
	ctrl     *gomock.Controller
	recorder *MockPackageControllerMockRecorder
}

// MockPackageControllerMockRecorder is the mock recorder for MockPackageController.
type MockPackageControllerMockRecorder struct {
	mock *MockPackageController
}

// NewMockPackageController creates a new mock instance.
func NewMockPackageController(ctrl *gomock.Controller) *MockPackageController {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageController) EXPECT() *MockPackageControllerMockRecorder {
	_ = "STUB: not implemented"

	// Enable mocks base method.
	return nil
}

func (m *MockPackageController) Enable(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Enable indicates an expected call of Enable.
func (mr *MockPackageControllerMockRecorder) Enable(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsInstalled mocks base method.
func (m *MockPackageController) IsInstalled(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// IsInstalled indicates an expected call of IsInstalled.
func (mr *MockPackageControllerMockRecorder) IsInstalled(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPackageHandler is a mock of PackageHandler interface.
type MockPackageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPackageHandlerMockRecorder
}

// MockPackageHandlerMockRecorder is the mock recorder for MockPackageHandler.
type MockPackageHandlerMockRecorder struct {
	mock *MockPackageHandler
}

// NewMockPackageHandler creates a new mock instance.
func NewMockPackageHandler(ctrl *gomock.Controller) *MockPackageHandler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageHandler) EXPECT() *MockPackageHandlerMockRecorder {
	_ = "STUB: not implemented"

	// CreatePackages mocks base method.
	return nil
}

func (m *MockPackageHandler) CreatePackages(ctx context.Context, fileName, kubeConfig string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreatePackages indicates an expected call of CreatePackages.
func (mr *MockPackageHandlerMockRecorder) CreatePackages(ctx, fileName, kubeConfig interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
