// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/curatedpackages/bundle.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/release/api/v1alpha1"
	gomock "github.com/golang/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	_ = "STUB: not implemented"

	// ReadBundlesForVersion mocks base method.
	return nil
}

func (m *MockReader) ReadBundlesForVersion(eksaVersion string) (*v1alpha1.Bundles, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadBundlesForVersion indicates an expected call of ReadBundlesForVersion.
func (mr *MockReaderMockRecorder) ReadBundlesForVersion(eksaVersion interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBundleRegistry is a mock of BundleRegistry interface.
type MockBundleRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockBundleRegistryMockRecorder
}

// MockBundleRegistryMockRecorder is the mock recorder for MockBundleRegistry.
type MockBundleRegistryMockRecorder struct {
	mock *MockBundleRegistry
}

// NewMockBundleRegistry creates a new mock instance.
func NewMockBundleRegistry(ctrl *gomock.Controller) *MockBundleRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleRegistry) EXPECT() *MockBundleRegistryMockRecorder {
	_ = "STUB: not implemented"

	// GetRegistryBaseRef mocks base method.
	return nil
}

func (m *MockBundleRegistry) GetRegistryBaseRef(ctx context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetRegistryBaseRef indicates an expected call of GetRegistryBaseRef.
func (mr *MockBundleRegistryMockRecorder) GetRegistryBaseRef(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
