// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/providers/docker (interfaces: ProviderClient,ProviderKubectlClient,KubeconfigReader)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	executables "github.com/aws/eks-anywhere/pkg/executables"
	types "github.com/aws/eks-anywhere/pkg/types"
	v1beta1 "github.com/aws/etcdadm-controller/api/v1beta1"
	gomock "github.com/golang/mock/gomock"
	v1beta2 "sigs.k8s.io/cluster-api/api/controlplane/kubeadm/v1beta2"
	v1beta20 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MockProviderClient is a mock of ProviderClient interface.
type MockProviderClient struct {
	ctrl     *gomock.Controller
	recorder *MockProviderClientMockRecorder
}

// MockProviderClientMockRecorder is the mock recorder for MockProviderClient.
type MockProviderClientMockRecorder struct {
	mock *MockProviderClient
}

// NewMockProviderClient creates a new mock instance.
func NewMockProviderClient(ctrl *gomock.Controller) *MockProviderClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderClient) EXPECT() *MockProviderClientMockRecorder {
	_ = "STUB: not implemented"

	// GetDockerLBPort mocks base method.
	return nil
}

func (m *MockProviderClient) GetDockerLBPort(arg0 context.Context, arg1 string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetDockerLBPort indicates an expected call of GetDockerLBPort.
func (mr *MockProviderClientMockRecorder) GetDockerLBPort(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockProviderKubectlClient is a mock of ProviderKubectlClient interface.
type MockProviderKubectlClient struct {
	ctrl     *gomock.Controller
	recorder *MockProviderKubectlClientMockRecorder
}

// MockProviderKubectlClientMockRecorder is the mock recorder for MockProviderKubectlClient.
type MockProviderKubectlClientMockRecorder struct {
	mock *MockProviderKubectlClient
}

// NewMockProviderKubectlClient creates a new mock instance.
func NewMockProviderKubectlClient(ctrl *gomock.Controller) *MockProviderKubectlClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderKubectlClient) EXPECT() *MockProviderKubectlClientMockRecorder {
	_ = "STUB: not implemented"

	// GetEksaCluster mocks base method.
	return nil
}

func (m *MockProviderKubectlClient) GetEksaCluster(arg0 context.Context, arg1 *types.Cluster, arg2 string) (*v1alpha1.Cluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEksaCluster indicates an expected call of GetEksaCluster.
func (mr *MockProviderKubectlClientMockRecorder) GetEksaCluster(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEtcdadmCluster mocks base method.
func (m *MockProviderKubectlClient) GetEtcdadmCluster(arg0 context.Context, arg1 *types.Cluster, arg2 string, arg3 ...executables.KubectlOpt) (*v1beta1.EtcdadmCluster, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEtcdadmCluster indicates an expected call of GetEtcdadmCluster.
func (mr *MockProviderKubectlClientMockRecorder) GetEtcdadmCluster(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetKubeadmControlPlane mocks base method.
func (m *MockProviderKubectlClient) GetKubeadmControlPlane(arg0 context.Context, arg1 *types.Cluster, arg2 string, arg3 ...executables.KubectlOpt) (*v1beta2.KubeadmControlPlane, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetKubeadmControlPlane indicates an expected call of GetKubeadmControlPlane.
func (mr *MockProviderKubectlClientMockRecorder) GetKubeadmControlPlane(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMachineDeployment mocks base method.
func (m *MockProviderKubectlClient) GetMachineDeployment(arg0 context.Context, arg1 string, arg2 ...executables.KubectlOpt) (*v1beta20.MachineDeployment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMachineDeployment indicates an expected call of GetMachineDeployment.
func (mr *MockProviderKubectlClientMockRecorder) GetMachineDeployment(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation mocks base method.
func (m *MockProviderKubectlClient) UpdateAnnotation(arg0 context.Context, arg1, arg2 string, arg3 map[string]string, arg4 ...executables.KubectlOpt) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateAnnotation indicates an expected call of UpdateAnnotation.
func (mr *MockProviderKubectlClientMockRecorder) UpdateAnnotation(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubeconfigReader is a mock of KubeconfigReader interface.
type MockKubeconfigReader struct {
	ctrl     *gomock.Controller
	recorder *MockKubeconfigReaderMockRecorder
}

// MockKubeconfigReaderMockRecorder is the mock recorder for MockKubeconfigReader.
type MockKubeconfigReaderMockRecorder struct {
	mock *MockKubeconfigReader
}

// NewMockKubeconfigReader creates a new mock instance.
func NewMockKubeconfigReader(ctrl *gomock.Controller) *MockKubeconfigReader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeconfigReader) EXPECT() *MockKubeconfigReaderMockRecorder {
	_ = "STUB: not implemented"

	// GetClusterKubeconfig mocks base method.
	return nil
}

func (m *MockKubeconfigReader) GetClusterKubeconfig(arg0 context.Context, arg1, arg2 string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetClusterKubeconfig indicates an expected call of GetClusterKubeconfig.
func (mr *MockKubeconfigReaderMockRecorder) GetClusterKubeconfig(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
