// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/kubernetes/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	kubernetes "github.com/aws/eks-anywhere/pkg/clients/kubernetes"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// ApplyServerSide mocks base method.
	return nil
}

func (m *MockClient) ApplyServerSide(ctx context.Context, fieldManager string, obj kubernetes.Object, opts ...kubernetes.ApplyServerSideOption) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplyServerSide indicates an expected call of ApplyServerSide.
func (mr *MockClientMockRecorder) ApplyServerSide(ctx, fieldManager, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf mocks base method.
func (m *MockClient) DeleteAllOf(ctx context.Context, obj kubernetes.Object, opts ...kubernetes.DeleteAllOfOption) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf indicates an expected call of DeleteAllOf.
func (mr *MockClientMockRecorder) DeleteAllOf(ctx, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, name, namespace string, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, name, namespace, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, list kubernetes.ObjectList, opts ...kubernetes.ListOption) error {
	_ = "STUB: not implemented"
	return nil
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, list interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Patch mocks base method.
func (m *MockClient) Patch(ctx context.Context, obj kubernetes.Object, patch kubernetes.Patch, opts ...kubernetes.PatchOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch indicates an expected call of Patch.
func (mr *MockClientMockRecorder) Patch(ctx, obj, patch interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockClient) Update(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Update indicates an expected call of Update.
func (mr *MockClientMockRecorder) Update(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockReader) Get(ctx context.Context, name, namespace string, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockReaderMockRecorder) Get(ctx, name, namespace, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockReader) List(ctx context.Context, list kubernetes.ObjectList, opts ...kubernetes.ListOption) error {
	_ = "STUB: not implemented"
	return nil
}

// List indicates an expected call of List.
func (mr *MockReaderMockRecorder) List(ctx, list interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockListOption is a mock of ListOption interface.
type MockListOption struct {
	ctrl     *gomock.Controller
	recorder *MockListOptionMockRecorder
}

// MockListOptionMockRecorder is the mock recorder for MockListOption.
type MockListOptionMockRecorder struct {
	mock *MockListOption
}

// NewMockListOption creates a new mock instance.
func NewMockListOption(ctrl *gomock.Controller) *MockListOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListOption) EXPECT() *MockListOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToList mocks base method.
	return nil
}

func (m *MockListOption) ApplyToList(arg0 *kubernetes.ListOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToList indicates an expected call of ApplyToList.
func (mr *MockListOptionMockRecorder) ApplyToList(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	_ = "STUB: not implemented"

	// ApplyServerSide mocks base method.
	return nil
}

func (m *MockWriter) ApplyServerSide(ctx context.Context, fieldManager string, obj kubernetes.Object, opts ...kubernetes.ApplyServerSideOption) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplyServerSide indicates an expected call of ApplyServerSide.
func (mr *MockWriterMockRecorder) ApplyServerSide(ctx, fieldManager, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockWriter) Create(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Create indicates an expected call of Create.
func (mr *MockWriterMockRecorder) Create(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockWriter) Delete(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockWriterMockRecorder) Delete(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf mocks base method.
func (m *MockWriter) DeleteAllOf(ctx context.Context, obj kubernetes.Object, opts ...kubernetes.DeleteAllOfOption) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteAllOf indicates an expected call of DeleteAllOf.
func (mr *MockWriterMockRecorder) DeleteAllOf(ctx, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Patch mocks base method.
func (m *MockWriter) Patch(ctx context.Context, obj kubernetes.Object, patch kubernetes.Patch, opts ...kubernetes.PatchOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch indicates an expected call of Patch.
func (mr *MockWriterMockRecorder) Patch(ctx, obj, patch interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockWriter) Update(ctx context.Context, obj kubernetes.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Update indicates an expected call of Update.
func (mr *MockWriterMockRecorder) Update(ctx, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPatchOption is a mock of PatchOption interface.
type MockPatchOption struct {
	ctrl     *gomock.Controller
	recorder *MockPatchOptionMockRecorder
}

// MockPatchOptionMockRecorder is the mock recorder for MockPatchOption.
type MockPatchOptionMockRecorder struct {
	mock *MockPatchOption
}

// NewMockPatchOption creates a new mock instance.
func NewMockPatchOption(ctrl *gomock.Controller) *MockPatchOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatchOption) EXPECT() *MockPatchOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToPatch mocks base method.
	return nil
}

func (m *MockPatchOption) ApplyToPatch(arg0 *kubernetes.PatchOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToPatch indicates an expected call of ApplyToPatch.
func (mr *MockPatchOptionMockRecorder) ApplyToPatch(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockDeleteAllOfOption is a mock of DeleteAllOfOption interface.
type MockDeleteAllOfOption struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteAllOfOptionMockRecorder
}

// MockDeleteAllOfOptionMockRecorder is the mock recorder for MockDeleteAllOfOption.
type MockDeleteAllOfOptionMockRecorder struct {
	mock *MockDeleteAllOfOption
}

// NewMockDeleteAllOfOption creates a new mock instance.
func NewMockDeleteAllOfOption(ctrl *gomock.Controller) *MockDeleteAllOfOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteAllOfOption) EXPECT() *MockDeleteAllOfOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToDeleteAllOf mocks base method.
	return nil
}

func (m *MockDeleteAllOfOption) ApplyToDeleteAllOf(arg0 *kubernetes.DeleteAllOfOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToDeleteAllOf indicates an expected call of ApplyToDeleteAllOf.
func (mr *MockDeleteAllOfOptionMockRecorder) ApplyToDeleteAllOf(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockApplyServerSideOption is a mock of ApplyServerSideOption interface.
type MockApplyServerSideOption struct {
	ctrl     *gomock.Controller
	recorder *MockApplyServerSideOptionMockRecorder
}

// MockApplyServerSideOptionMockRecorder is the mock recorder for MockApplyServerSideOption.
type MockApplyServerSideOptionMockRecorder struct {
	mock *MockApplyServerSideOption
}

// NewMockApplyServerSideOption creates a new mock instance.
func NewMockApplyServerSideOption(ctrl *gomock.Controller) *MockApplyServerSideOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplyServerSideOption) EXPECT() *MockApplyServerSideOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToApplyServerSide mocks base method.
	return nil
}

func (m *MockApplyServerSideOption) ApplyToApplyServerSide(arg0 *kubernetes.ApplyServerSideOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToApplyServerSide indicates an expected call of ApplyToApplyServerSide.
func (mr *MockApplyServerSideOptionMockRecorder) ApplyToApplyServerSide(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
