// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/kubernetes/kubectl.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	kubernetes "github.com/aws/eks-anywhere/pkg/clients/kubernetes"
	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockKubectl is a mock of Kubectl interface.
type MockKubectl struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlMockRecorder
}

// MockKubectlMockRecorder is the mock recorder for MockKubectl.
type MockKubectlMockRecorder struct {
	mock *MockKubectl
}

// NewMockKubectl creates a new mock instance.
func NewMockKubectl(ctrl *gomock.Controller) *MockKubectl { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectl) EXPECT() *MockKubectlMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *MockKubectl) Apply(ctx context.Context, kubeconfig string, obj runtime.Object, opts ...kubernetes.KubectlApplyOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Apply indicates an expected call of Apply.
func (mr *MockKubectlMockRecorder) Apply(ctx, kubeconfig, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockKubectl) Create(ctx context.Context, kubeconfig string, obj runtime.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Create indicates an expected call of Create.
func (mr *MockKubectlMockRecorder) Create(ctx, kubeconfig, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockKubectl) Delete(ctx context.Context, resourceType, kubeconfig string, opts ...kubernetes.KubectlDeleteOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockKubectlMockRecorder) Delete(ctx, resourceType, kubeconfig interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockKubectl) Get(ctx context.Context, resourceType, kubeconfig string, obj runtime.Object, opts ...kubernetes.KubectlGetOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockKubectlMockRecorder) Get(ctx, resourceType, kubeconfig, obj interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Replace mocks base method.
func (m *MockKubectl) Replace(ctx context.Context, kubeconfig string, obj runtime.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// Replace indicates an expected call of Replace.
func (mr *MockKubectlMockRecorder) Replace(ctx, kubeconfig, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubectlGetOption is a mock of KubectlGetOption interface.
type MockKubectlGetOption struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlGetOptionMockRecorder
}

// MockKubectlGetOptionMockRecorder is the mock recorder for MockKubectlGetOption.
type MockKubectlGetOptionMockRecorder struct {
	mock *MockKubectlGetOption
}

// NewMockKubectlGetOption creates a new mock instance.
func NewMockKubectlGetOption(ctrl *gomock.Controller) *MockKubectlGetOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectlGetOption) EXPECT() *MockKubectlGetOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToGet mocks base method.
	return nil
}

func (m *MockKubectlGetOption) ApplyToGet(arg0 *kubernetes.KubectlGetOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToGet indicates an expected call of ApplyToGet.
func (mr *MockKubectlGetOptionMockRecorder) ApplyToGet(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubectlApplyOption is a mock of KubectlApplyOption interface.
type MockKubectlApplyOption struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlApplyOptionMockRecorder
}

// MockKubectlApplyOptionMockRecorder is the mock recorder for MockKubectlApplyOption.
type MockKubectlApplyOptionMockRecorder struct {
	mock *MockKubectlApplyOption
}

// NewMockKubectlApplyOption creates a new mock instance.
func NewMockKubectlApplyOption(ctrl *gomock.Controller) *MockKubectlApplyOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectlApplyOption) EXPECT() *MockKubectlApplyOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToApply mocks base method.
	return nil
}

func (m *MockKubectlApplyOption) ApplyToApply(arg0 *kubernetes.KubectlApplyOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToApply indicates an expected call of ApplyToApply.
func (mr *MockKubectlApplyOptionMockRecorder) ApplyToApply(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubectlDeleteOption is a mock of KubectlDeleteOption interface.
type MockKubectlDeleteOption struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlDeleteOptionMockRecorder
}

// MockKubectlDeleteOptionMockRecorder is the mock recorder for MockKubectlDeleteOption.
type MockKubectlDeleteOptionMockRecorder struct {
	mock *MockKubectlDeleteOption
}

// NewMockKubectlDeleteOption creates a new mock instance.
func NewMockKubectlDeleteOption(ctrl *gomock.Controller) *MockKubectlDeleteOption {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectlDeleteOption) EXPECT() *MockKubectlDeleteOptionMockRecorder {
	_ = "STUB: not implemented"

	// ApplyToDelete mocks base method.
	return nil
}

func (m *MockKubectlDeleteOption) ApplyToDelete(arg0 *kubernetes.KubectlDeleteOptions) {
	_ = "STUB: not implemented"
	return
}

// ApplyToDelete indicates an expected call of ApplyToDelete.
func (mr *MockKubectlDeleteOptionMockRecorder) ApplyToDelete(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
