// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clusterapi/manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	clusterapi "github.com/aws/eks-anywhere/pkg/clusterapi"
	providers "github.com/aws/eks-anywhere/pkg/providers"
	types "github.com/aws/eks-anywhere/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockCAPIClient is a mock of CAPIClient interface.
type MockCAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockCAPIClientMockRecorder
}

// MockCAPIClientMockRecorder is the mock recorder for MockCAPIClient.
type MockCAPIClientMockRecorder struct {
	mock *MockCAPIClient
}

// NewMockCAPIClient creates a new mock instance.
func NewMockCAPIClient(ctrl *gomock.Controller) *MockCAPIClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCAPIClient) EXPECT() *MockCAPIClientMockRecorder {
	_ = "STUB: not implemented"

	// InstallEtcdadmProviders mocks base method.
	return nil
}

func (m *MockCAPIClient) InstallEtcdadmProviders(ctx context.Context, managementComponents *cluster.ManagementComponents, clusterSpec *cluster.Spec, cluster *types.Cluster, provider providers.Provider, installProviders []string) error {
	_ = "STUB: not implemented"
	return nil
}

// InstallEtcdadmProviders indicates an expected call of InstallEtcdadmProviders.
func (mr *MockCAPIClientMockRecorder) InstallEtcdadmProviders(ctx, managementComponents, clusterSpec, cluster, provider, installProviders interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Upgrade mocks base method.
func (m *MockCAPIClient) Upgrade(ctx context.Context, managementCluster *types.Cluster, provider providers.Provider, managementComponents *cluster.ManagementComponents, newSpec *cluster.Spec, changeDiff *clusterapi.CAPIChangeDiff) error {
	_ = "STUB: not implemented"
	return nil
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockCAPIClientMockRecorder) Upgrade(ctx, managementCluster, provider, managementComponents, newSpec, changeDiff interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockKubectlClient is a mock of KubectlClient interface.
type MockKubectlClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlClientMockRecorder
}

// MockKubectlClientMockRecorder is the mock recorder for MockKubectlClient.
type MockKubectlClientMockRecorder struct {
	mock *MockKubectlClient
}

// NewMockKubectlClient creates a new mock instance.
func NewMockKubectlClient(ctrl *gomock.Controller) *MockKubectlClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubectlClient) EXPECT() *MockKubectlClientMockRecorder {
	_ = "STUB: not implemented"

	// CheckProviderExists mocks base method.
	return nil
}

func (m *MockKubectlClient) CheckProviderExists(ctx context.Context, kubeconfigFile, name, namespace string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// CheckProviderExists indicates an expected call of CheckProviderExists.
func (mr *MockKubectlClientMockRecorder) CheckProviderExists(ctx, kubeconfigFile, name, namespace interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
