// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/validations/createcluster/createcluster.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	validations "github.com/aws/eks-anywhere/pkg/validations"
	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	_ = "STUB: not implemented"

	// PreflightValidations mocks base method.
	return nil
}

func (m *MockValidator) PreflightValidations(ctx context.Context) []validations.Validation {
	_ = "STUB: not implemented"
	return nil
}

// PreflightValidations indicates an expected call of PreflightValidations.
func (mr *MockValidatorMockRecorder) PreflightValidations(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
