// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/git (interfaces: Client,ProviderClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	git "github.com/aws/eks-anywhere/pkg/git"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockClient) Add(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockClientMockRecorder) Add(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Branch mocks base method.
func (m *MockClient) Branch(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Branch indicates an expected call of Branch.
func (mr *MockClientMockRecorder) Branch(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Clone mocks base method.
func (m *MockClient) Clone(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Clone indicates an expected call of Clone.
func (mr *MockClientMockRecorder) Clone(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Commit mocks base method.
func (m *MockClient) Commit(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockClientMockRecorder) Commit(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockClient) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockClientMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Pull mocks base method.
func (m *MockClient) Pull(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// Pull indicates an expected call of Pull.
func (mr *MockClientMockRecorder) Pull(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Push mocks base method.
func (m *MockClient) Push(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Push indicates an expected call of Push.
func (mr *MockClientMockRecorder) Push(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Remove mocks base method.
func (m *MockClient) Remove(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Remove indicates an expected call of Remove.
func (mr *MockClientMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateRemoteExists mocks base method.
func (m *MockClient) ValidateRemoteExists(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateRemoteExists indicates an expected call of ValidateRemoteExists.
func (mr *MockClientMockRecorder) ValidateRemoteExists(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockProviderClient is a mock of ProviderClient interface.
type MockProviderClient struct {
	ctrl     *gomock.Controller
	recorder *MockProviderClientMockRecorder
}

// MockProviderClientMockRecorder is the mock recorder for MockProviderClient.
type MockProviderClientMockRecorder struct {
	mock *MockProviderClient
}

// NewMockProviderClient creates a new mock instance.
func NewMockProviderClient(ctrl *gomock.Controller) *MockProviderClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderClient) EXPECT() *MockProviderClientMockRecorder {
	_ = "STUB: not implemented"

	// AddDeployKeyToRepo mocks base method.
	return nil
}

func (m *MockProviderClient) AddDeployKeyToRepo(arg0 context.Context, arg1 git.AddDeployKeyOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// AddDeployKeyToRepo indicates an expected call of AddDeployKeyToRepo.
func (mr *MockProviderClientMockRecorder) AddDeployKeyToRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateRepo mocks base method.
func (m *MockProviderClient) CreateRepo(arg0 context.Context, arg1 git.CreateRepoOpts) (*git.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateRepo indicates an expected call of CreateRepo.
func (mr *MockProviderClientMockRecorder) CreateRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRepo mocks base method.
func (m *MockProviderClient) DeleteRepo(arg0 context.Context, arg1 git.DeleteRepoOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRepo indicates an expected call of DeleteRepo.
func (mr *MockProviderClientMockRecorder) DeleteRepo(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRepo mocks base method.
func (m *MockProviderClient) GetRepo(arg0 context.Context) (*git.Repository, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockProviderClientMockRecorder) GetRepo(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PathExists mocks base method.
func (m *MockProviderClient) PathExists(arg0 context.Context, arg1, arg2, arg3, arg4 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// PathExists indicates an expected call of PathExists.
func (mr *MockProviderClientMockRecorder) PathExists(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Validate mocks base method.
func (m *MockProviderClient) Validate(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate indicates an expected call of Validate.
func (mr *MockProviderClientMockRecorder) Validate(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
