// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/awsiamauth/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	types "github.com/aws/eks-anywhere/pkg/types"
	gomock "github.com/golang/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// ApplyKubeSpecFromBytes mocks base method.
	return nil
}

func (m *MockClient) ApplyKubeSpecFromBytes(ctx context.Context, cluster *types.Cluster, data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplyKubeSpecFromBytes indicates an expected call of ApplyKubeSpecFromBytes.
func (mr *MockClientMockRecorder) ApplyKubeSpecFromBytes(ctx, cluster, data interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetApiServerUrl mocks base method.
func (m *MockClient) GetApiServerUrl(ctx context.Context, cluster *types.Cluster) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetApiServerUrl indicates an expected call of GetApiServerUrl.
func (mr *MockClientMockRecorder) GetApiServerUrl(ctx, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *MockClient) GetObject(ctx context.Context, resourceType, name, namespace, kubeconfig string, obj runtime.Object) error {
	_ = "STUB: not implemented"
	return nil
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientMockRecorder) GetObject(ctx, resourceType, name, namespace, kubeconfig, obj interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
