// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/cluster_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	controller "github.com/aws/eks-anywhere/pkg/controller"
	clusters "github.com/aws/eks-anywhere/pkg/controller/clusters"
	curatedpackages "github.com/aws/eks-anywhere/pkg/curatedpackages"
	vsphere "github.com/aws/eks-anywhere/pkg/providers/vsphere"
	registrymirror "github.com/aws/eks-anywhere/pkg/registrymirror"
	v1alpha10 "github.com/aws/eks-anywhere/release/api/v1alpha1"
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockPackagesClient is a mock of PackagesClient interface.
type MockPackagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockPackagesClientMockRecorder
}

// MockPackagesClientMockRecorder is the mock recorder for MockPackagesClient.
type MockPackagesClientMockRecorder struct {
	mock *MockPackagesClient
}

// NewMockPackagesClient creates a new mock instance.
func NewMockPackagesClient(ctrl *gomock.Controller) *MockPackagesClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackagesClient) EXPECT() *MockPackagesClientMockRecorder {
	_ = "STUB: not implemented"

	// EnableFullLifecycle mocks base method.
	return nil
}

func (m *MockPackagesClient) EnableFullLifecycle(ctx context.Context, log logr.Logger, clusterName, kubeConfig string, chart *v1alpha10.Image, registry *registrymirror.RegistryMirror, options ...curatedpackages.PackageControllerClientOpt) error {
	_ = "STUB: not implemented"
	return nil
}

// EnableFullLifecycle indicates an expected call of EnableFullLifecycle.
func (mr *MockPackagesClientMockRecorder) EnableFullLifecycle(ctx, log, clusterName, kubeConfig, chart, registry interface{}, options ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile mocks base method.
func (m *MockPackagesClient) Reconcile(arg0 context.Context, arg1 logr.Logger, arg2 client.Client, arg3 *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockPackagesClientMockRecorder) Reconcile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileDelete mocks base method.
func (m *MockPackagesClient) ReconcileDelete(arg0 context.Context, arg1 logr.Logger, arg2 curatedpackages.KubeDeleter, arg3 *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileDelete indicates an expected call of ReconcileDelete.
func (mr *MockPackagesClientMockRecorder) ReconcileDelete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockProviderClusterReconcilerRegistry is a mock of ProviderClusterReconcilerRegistry interface.
type MockProviderClusterReconcilerRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockProviderClusterReconcilerRegistryMockRecorder
}

// MockProviderClusterReconcilerRegistryMockRecorder is the mock recorder for MockProviderClusterReconcilerRegistry.
type MockProviderClusterReconcilerRegistryMockRecorder struct {
	mock *MockProviderClusterReconcilerRegistry
}

// NewMockProviderClusterReconcilerRegistry creates a new mock instance.
func NewMockProviderClusterReconcilerRegistry(ctrl *gomock.Controller) *MockProviderClusterReconcilerRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderClusterReconcilerRegistry) EXPECT() *MockProviderClusterReconcilerRegistryMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockProviderClusterReconcilerRegistry) Get(datacenterKind string) clusters.ProviderClusterReconciler {
	_ = "STUB: not implemented"
	return *new(clusters.ProviderClusterReconciler)
}

// Get indicates an expected call of Get.
func (mr *MockProviderClusterReconcilerRegistryMockRecorder) Get(datacenterKind interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAWSIamConfigReconciler is a mock of AWSIamConfigReconciler interface.
type MockAWSIamConfigReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockAWSIamConfigReconcilerMockRecorder
}

// MockAWSIamConfigReconcilerMockRecorder is the mock recorder for MockAWSIamConfigReconciler.
type MockAWSIamConfigReconcilerMockRecorder struct {
	mock *MockAWSIamConfigReconciler
}

// NewMockAWSIamConfigReconciler creates a new mock instance.
func NewMockAWSIamConfigReconciler(ctrl *gomock.Controller) *MockAWSIamConfigReconciler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSIamConfigReconciler) EXPECT() *MockAWSIamConfigReconcilerMockRecorder {
	_ = "STUB: not implemented"

	// EnsureCASecret mocks base method.
	return nil
}

func (m *MockAWSIamConfigReconciler) EnsureCASecret(ctx context.Context, logger logr.Logger, cluster *v1alpha1.Cluster) (controller.Result, error) {
	_ = "STUB: not implemented"
	return *new(controller.Result), nil
}

// EnsureCASecret indicates an expected call of EnsureCASecret.
func (mr *MockAWSIamConfigReconcilerMockRecorder) EnsureCASecret(ctx, logger, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile mocks base method.
func (m *MockAWSIamConfigReconciler) Reconcile(ctx context.Context, logger logr.Logger, cluster *v1alpha1.Cluster) (controller.Result, error) {
	_ = "STUB: not implemented"
	return *new(controller.Result), nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockAWSIamConfigReconcilerMockRecorder) Reconcile(ctx, logger, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileDelete mocks base method.
func (m *MockAWSIamConfigReconciler) ReconcileDelete(ctx context.Context, logger logr.Logger, cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileDelete indicates an expected call of ReconcileDelete.
func (mr *MockAWSIamConfigReconcilerMockRecorder) ReconcileDelete(ctx, logger, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileWorkloadClusterDelete mocks base method.
func (m *MockAWSIamConfigReconciler) ReconcileWorkloadClusterDelete(ctx context.Context, logger logr.Logger, cluster *v1alpha1.Cluster, awsIamConfig *v1alpha1.AWSIamConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileWorkloadClusterDelete indicates an expected call of ReconcileWorkloadClusterDelete.
func (mr *MockAWSIamConfigReconcilerMockRecorder) ReconcileWorkloadClusterDelete(ctx, logger, cluster, awsIamConfig interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMachineHealthCheckReconciler is a mock of MachineHealthCheckReconciler interface.
type MockMachineHealthCheckReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockMachineHealthCheckReconcilerMockRecorder
}

// MockMachineHealthCheckReconcilerMockRecorder is the mock recorder for MockMachineHealthCheckReconciler.
type MockMachineHealthCheckReconcilerMockRecorder struct {
	mock *MockMachineHealthCheckReconciler
}

// NewMockMachineHealthCheckReconciler creates a new mock instance.
func NewMockMachineHealthCheckReconciler(ctrl *gomock.Controller) *MockMachineHealthCheckReconciler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineHealthCheckReconciler) EXPECT() *MockMachineHealthCheckReconcilerMockRecorder {
	_ = "STUB: not implemented"

	// Reconcile mocks base method.
	return nil
}

func (m *MockMachineHealthCheckReconciler) Reconcile(ctx context.Context, logger logr.Logger, cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockMachineHealthCheckReconcilerMockRecorder) Reconcile(ctx, logger, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockClusterValidator is a mock of ClusterValidator interface.
type MockClusterValidator struct {
	ctrl     *gomock.Controller
	recorder *MockClusterValidatorMockRecorder
}

// MockClusterValidatorMockRecorder is the mock recorder for MockClusterValidator.
type MockClusterValidatorMockRecorder struct {
	mock *MockClusterValidator
}

// NewMockClusterValidator creates a new mock instance.
func NewMockClusterValidator(ctrl *gomock.Controller) *MockClusterValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterValidator) EXPECT() *MockClusterValidatorMockRecorder {
	_ = "STUB: not implemented"

	// ValidateManagementClusterName mocks base method.
	return nil
}

func (m *MockClusterValidator) ValidateManagementClusterName(ctx context.Context, log logr.Logger, cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateManagementClusterName indicates an expected call of ValidateManagementClusterName.
func (mr *MockClusterValidatorMockRecorder) ValidateManagementClusterName(ctx, log, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSpecBuilder is a mock of SpecBuilder interface.
type MockSpecBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSpecBuilderMockRecorder
}

// MockSpecBuilderMockRecorder is the mock recorder for MockSpecBuilder.
type MockSpecBuilderMockRecorder struct {
	mock *MockSpecBuilder
}

// NewMockSpecBuilder creates a new mock instance.
func NewMockSpecBuilder(ctrl *gomock.Controller) *MockSpecBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecBuilder) EXPECT() *MockSpecBuilderMockRecorder {
	_ = "STUB: not implemented"

	// BuildSpec mocks base method.
	return nil
}

func (m *MockSpecBuilder) BuildSpec(ctx context.Context, eksaCluster *v1alpha1.Cluster) (*cluster.Spec, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BuildSpec indicates an expected call of BuildSpec.
func (mr *MockSpecBuilderMockRecorder) BuildSpec(ctx, eksaCluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockFailureDomainSpecBuilder is a mock of FailureDomainSpecBuilder interface.
type MockFailureDomainSpecBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockFailureDomainSpecBuilderMockRecorder
}

// MockFailureDomainSpecBuilderMockRecorder is the mock recorder for MockFailureDomainSpecBuilder.
type MockFailureDomainSpecBuilderMockRecorder struct {
	mock *MockFailureDomainSpecBuilder
}

// NewMockFailureDomainSpecBuilder creates a new mock instance.
func NewMockFailureDomainSpecBuilder(ctrl *gomock.Controller) *MockFailureDomainSpecBuilder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureDomainSpecBuilder) EXPECT() *MockFailureDomainSpecBuilderMockRecorder {
	_ = "STUB: not implemented"

	// BuildFailureDomainSpec mocks base method.
	return nil
}

func (m *MockFailureDomainSpecBuilder) BuildFailureDomainSpec(log logr.Logger, clusterSpec *cluster.Spec) (*vsphere.FailureDomains, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BuildFailureDomainSpec indicates an expected call of BuildFailureDomainSpec.
func (mr *MockFailureDomainSpecBuilderMockRecorder) BuildFailureDomainSpec(log, clusterSpec interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockObjectReconciler is a mock of ObjectReconciler interface.
type MockObjectReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockObjectReconcilerMockRecorder
}

// MockObjectReconcilerMockRecorder is the mock recorder for MockObjectReconciler.
type MockObjectReconcilerMockRecorder struct {
	mock *MockObjectReconciler
}

// NewMockObjectReconciler creates a new mock instance.
func NewMockObjectReconciler(ctrl *gomock.Controller) *MockObjectReconciler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectReconciler) EXPECT() *MockObjectReconcilerMockRecorder {
	_ = "STUB: not implemented"

	// ReconcileObjects mocks base method.
	return nil
}

func (m *MockObjectReconciler) ReconcileObjects(ctx context.Context, fd *vsphere.FailureDomains) error {
	_ = "STUB: not implemented"
	return nil
}

// ReconcileObjects indicates an expected call of ReconcileObjects.
func (mr *MockObjectReconcilerMockRecorder) ReconcileObjects(ctx, fd interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockFailureDomainApplier is a mock of FailureDomainApplier interface.
type MockFailureDomainApplier struct {
	ctrl     *gomock.Controller
	recorder *MockFailureDomainApplierMockRecorder
}

// MockFailureDomainApplierMockRecorder is the mock recorder for MockFailureDomainApplier.
type MockFailureDomainApplierMockRecorder struct {
	mock *MockFailureDomainApplier
}

// NewMockFailureDomainApplier creates a new mock instance.
func NewMockFailureDomainApplier(ctrl *gomock.Controller) *MockFailureDomainApplier {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureDomainApplier) EXPECT() *MockFailureDomainApplierMockRecorder {
	_ = "STUB: not implemented"

	// ApplyFailureDomains mocks base method.
	return nil
}

func (m *MockFailureDomainApplier) ApplyFailureDomains(ctx context.Context, log logr.Logger, cluster *v1alpha1.Cluster) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplyFailureDomains indicates an expected call of ApplyFailureDomains.
func (mr *MockFailureDomainApplierMockRecorder) ApplyFailureDomains(ctx, log, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
