// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/controllers (interfaces: Manager)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"

	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
	meta "k8s.io/apimachinery/pkg/api/meta"
	runtime "k8s.io/apimachinery/pkg/runtime"
	rest "k8s.io/client-go/rest"
	record "k8s.io/client-go/tools/record"
	cache "sigs.k8s.io/controller-runtime/pkg/cache"
	client "sigs.k8s.io/controller-runtime/pkg/client"
	config "sigs.k8s.io/controller-runtime/pkg/config"
	healthz "sigs.k8s.io/controller-runtime/pkg/healthz"
	manager "sigs.k8s.io/controller-runtime/pkg/manager"
	webhook "sigs.k8s.io/controller-runtime/pkg/webhook"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// Add mocks base method.
	return nil
}

func (m *MockManager) Add(arg0 manager.Runnable) error { _ = "STUB: not implemented"; return nil }

// Add indicates an expected call of Add.
func (mr *MockManagerMockRecorder) Add(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddHealthzCheck mocks base method.
func (m *MockManager) AddHealthzCheck(arg0 string, arg1 healthz.Checker) error {
	_ = "STUB: not implemented"
	return nil
}

// AddHealthzCheck indicates an expected call of AddHealthzCheck.
func (mr *MockManagerMockRecorder) AddHealthzCheck(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddMetricsServerExtraHandler mocks base method.
func (m *MockManager) AddMetricsServerExtraHandler(arg0 string, arg1 http.Handler) error {
	_ = "STUB: not implemented"
	return nil
}

// AddMetricsServerExtraHandler indicates an expected call of AddMetricsServerExtraHandler.
func (mr *MockManagerMockRecorder) AddMetricsServerExtraHandler(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddReadyzCheck mocks base method.
func (m *MockManager) AddReadyzCheck(arg0 string, arg1 healthz.Checker) error {
	_ = "STUB: not implemented"
	return nil
}

// AddReadyzCheck indicates an expected call of AddReadyzCheck.
func (mr *MockManagerMockRecorder) AddReadyzCheck(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Elected mocks base method.
func (m *MockManager) Elected() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// Elected indicates an expected call of Elected.
func (mr *MockManagerMockRecorder) Elected() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetAPIReader mocks base method.
func (m *MockManager) GetAPIReader() client.Reader {
	_ = "STUB: not implemented"
	return *new(client.Reader)
}

// GetAPIReader indicates an expected call of GetAPIReader.
func (mr *MockManagerMockRecorder) GetAPIReader() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCache mocks base method.
func (m *MockManager) GetCache() cache.Cache { _ = "STUB: not implemented"; return *new(cache.Cache) }

// GetCache indicates an expected call of GetCache.
func (mr *MockManagerMockRecorder) GetCache() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetClient mocks base method.
func (m *MockManager) GetClient() client.Client {
	_ = "STUB: not implemented"
	return *new(client.Client)
}

// GetClient indicates an expected call of GetClient.
func (mr *MockManagerMockRecorder) GetClient() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetConfig mocks base method.
func (m *MockManager) GetConfig() *rest.Config { _ = "STUB: not implemented"; return nil }

// GetConfig indicates an expected call of GetConfig.
func (mr *MockManagerMockRecorder) GetConfig() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetControllerOptions mocks base method.
func (m *MockManager) GetControllerOptions() config.Controller {
	_ = "STUB: not implemented"
	return *new(config.Controller)
}

// GetControllerOptions indicates an expected call of GetControllerOptions.
func (mr *MockManagerMockRecorder) GetControllerOptions() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventRecorderFor mocks base method.
func (m *MockManager) GetEventRecorderFor(arg0 string) record.EventRecorder {
	_ = "STUB: not implemented"
	return *new(record.EventRecorder)
}

// GetEventRecorderFor indicates an expected call of GetEventRecorderFor.
func (mr *MockManagerMockRecorder) GetEventRecorderFor(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFieldIndexer mocks base method.
func (m *MockManager) GetFieldIndexer() client.FieldIndexer {
	_ = "STUB: not implemented"
	return *new(client.FieldIndexer)
}

// GetFieldIndexer indicates an expected call of GetFieldIndexer.
func (mr *MockManagerMockRecorder) GetFieldIndexer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHTTPClient mocks base method.
func (m *MockManager) GetHTTPClient() *http.Client { _ = "STUB: not implemented"; return nil }

// GetHTTPClient indicates an expected call of GetHTTPClient.
func (mr *MockManagerMockRecorder) GetHTTPClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLogger mocks base method.
func (m *MockManager) GetLogger() logr.Logger { _ = "STUB: not implemented"; return *new(logr.Logger) }

// GetLogger indicates an expected call of GetLogger.
func (mr *MockManagerMockRecorder) GetLogger() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetRESTMapper mocks base method.
func (m *MockManager) GetRESTMapper() meta.RESTMapper {
	_ = "STUB: not implemented"
	return *new(meta.RESTMapper)
}

// GetRESTMapper indicates an expected call of GetRESTMapper.
func (mr *MockManagerMockRecorder) GetRESTMapper() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetScheme mocks base method.
func (m *MockManager) GetScheme() *runtime.Scheme { _ = "STUB: not implemented"; return nil }

// GetScheme indicates an expected call of GetScheme.
func (mr *MockManagerMockRecorder) GetScheme() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetWebhookServer mocks base method.
func (m *MockManager) GetWebhookServer() webhook.Server {
	_ = "STUB: not implemented"
	return *new(webhook.Server)
}

// GetWebhookServer indicates an expected call of GetWebhookServer.
func (mr *MockManagerMockRecorder) GetWebhookServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockManager) Start(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
