// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/controller/clusters/registry.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	controller "github.com/aws/eks-anywhere/pkg/controller"
	logr "github.com/go-logr/logr"
	gomock "github.com/golang/mock/gomock"
)

// MockProviderClusterReconciler is a mock of ProviderClusterReconciler interface.
type MockProviderClusterReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockProviderClusterReconcilerMockRecorder
}

// MockProviderClusterReconcilerMockRecorder is the mock recorder for MockProviderClusterReconciler.
type MockProviderClusterReconcilerMockRecorder struct {
	mock *MockProviderClusterReconciler
}

// NewMockProviderClusterReconciler creates a new mock instance.
func NewMockProviderClusterReconciler(ctrl *gomock.Controller) *MockProviderClusterReconciler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderClusterReconciler) EXPECT() *MockProviderClusterReconcilerMockRecorder {
	_ = "STUB: not implemented"

	// Reconcile mocks base method.
	return nil
}

func (m *MockProviderClusterReconciler) Reconcile(ctx context.Context, log logr.Logger, cluster *v1alpha1.Cluster) (controller.Result, error) {
	_ = "STUB: not implemented"
	return *new(controller.Result), nil
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockProviderClusterReconcilerMockRecorder) Reconcile(ctx, log, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
