// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/awsiamauth/reconciler/reconciler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockRemoteClientRegistry is a mock of RemoteClientRegistry interface.
type MockRemoteClientRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteClientRegistryMockRecorder
}

// MockRemoteClientRegistryMockRecorder is the mock recorder for MockRemoteClientRegistry.
type MockRemoteClientRegistryMockRecorder struct {
	mock *MockRemoteClientRegistry
}

// NewMockRemoteClientRegistry creates a new mock instance.
func NewMockRemoteClientRegistry(ctrl *gomock.Controller) *MockRemoteClientRegistry {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteClientRegistry) EXPECT() *MockRemoteClientRegistryMockRecorder {
	_ = "STUB: not implemented"

	// GetClient mocks base method.
	return nil
}

func (m *MockRemoteClientRegistry) GetClient(ctx context.Context, cluster client.ObjectKey) (client.Client, error) {
	_ = "STUB: not implemented"
	return *new(client.Client), nil
}

// GetClient indicates an expected call of GetClient.
func (mr *MockRemoteClientRegistryMockRecorder) GetClient(ctx, cluster interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
