//go:build e2e
// +build e2e

package e2e

import (
	"github.com/aws/eks-anywhere/test/framework"
)

func runSimpleFlow(test *framework.ClusterE2ETest) { _ = "STUB: not implemented"; return }

// runSimpleFlowWithoutClusterConfigGeneration runs the Create and Delete cluster flows
// that use the cluster config generated by the WithClusterConfig method when the test object
// is created, and avoids regenerating a cluster config with defaults.
func runSimpleFlowWithoutClusterConfigGeneration(test *framework.ClusterE2ETest) {
	_ = "STUB: not implemented"
	return
}

func runTinkerbellSimpleFlow(test *framework.ClusterE2ETest) { _ = "STUB: not implemented"; return }

// runTinkerbellSimpleFlowWithoutClusterConfigGeneration runs the Create and Delete cluster flows
// for Baremetal that use the cluster config generated by the WithClusterConfig method when the
// test object is created, and avoids regenerating a cluster config with defaults.
func runTinkerbellSimpleFlowWithoutClusterConfigGeneration(test *framework.ClusterE2ETest) {
	_ = "STUB: not implemented"
	return
}

// runSimpleFlowWithSecondNetworkValidation runs the Create and Delete cluster flows and validate the cluster with 2 interfaces get 2 IPs
func runSimpleFlowWithSecondNetworkValidation(test *framework.ClusterE2ETest, workerNodeWithSecondNetwork string) {
	_ = "STUB: not implemented"
	return
}
