// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/tinkerbell/hardware/translate.go

// Package mocks is a generated GoMock package.
package mocks

import (
	hardware "github.com/aws/eks-anywhere/pkg/providers/tinkerbell/hardware"
	gomock "github.com/golang/mock/gomock"
)

// MockMachineReader is a mock of MachineReader interface.
type MockMachineReader struct {
	ctrl     *gomock.Controller
	recorder *MockMachineReaderMockRecorder
}

// MockMachineReaderMockRecorder is the mock recorder for MockMachineReader.
type MockMachineReaderMockRecorder struct {
	mock *MockMachineReader
}

// NewMockMachineReader creates a new mock instance.
func NewMockMachineReader(ctrl *gomock.Controller) *MockMachineReader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineReader) EXPECT() *MockMachineReaderMockRecorder {
	_ = "STUB: not implemented"

	// Read mocks base method.
	return nil
}

func (m *MockMachineReader) Read() (hardware.Machine, error) {
	_ = "STUB: not implemented"
	return *new(hardware.Machine), nil
}

// Read indicates an expected call of Read.
func (mr *MockMachineReaderMockRecorder) Read() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockMachineWriter is a mock of MachineWriter interface.
type MockMachineWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMachineWriterMockRecorder
}

// MockMachineWriterMockRecorder is the mock recorder for MockMachineWriter.
type MockMachineWriterMockRecorder struct {
	mock *MockMachineWriter
}

// NewMockMachineWriter creates a new mock instance.
func NewMockMachineWriter(ctrl *gomock.Controller) *MockMachineWriter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineWriter) EXPECT() *MockMachineWriterMockRecorder {
	_ = "STUB: not implemented"

	// Write mocks base method.
	return nil
}

func (m *MockMachineWriter) Write(arg0 hardware.Machine) error {
	_ = "STUB: not implemented"
	return nil
}

// Write indicates an expected call of Write.
func (mr *MockMachineWriterMockRecorder) Write(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMachineValidator is a mock of MachineValidator interface.
type MockMachineValidator struct {
	ctrl     *gomock.Controller
	recorder *MockMachineValidatorMockRecorder
}

// MockMachineValidatorMockRecorder is the mock recorder for MockMachineValidator.
type MockMachineValidatorMockRecorder struct {
	mock *MockMachineValidator
}

// NewMockMachineValidator creates a new mock instance.
func NewMockMachineValidator(ctrl *gomock.Controller) *MockMachineValidator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineValidator) EXPECT() *MockMachineValidatorMockRecorder {
	_ = "STUB: not implemented"

	// Validate mocks base method.
	return nil
}

func (m *MockMachineValidator) Validate(arg0 hardware.Machine) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate indicates an expected call of Validate.
func (mr *MockMachineValidatorMockRecorder) Validate(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
